Repository CTStudyGroup/BOJ, pull requests merged in 2024-09, with the labels that each got.

#2 [BOJ 10870] 피보나치 수 5
  RecursiveFunction/BOJ10870/eunjin.py
Labels: 재귀함수

#7 [BOJ10870] 피보나치 수5/B2
  .DS_Store
  .gitignore
  BFS/.DS_Store
  RecursiveFunction/BOJ10870/.DS_Store
  RecursiveFunction/BOJ10870/이효림.py
Labels: Add, 재귀함수

#8 [BOJ 10870] 피보나치 수 5 / B2
  RecursiveFunction/BOJ10870/hyeonji.py
Labels: Add

#4 [BOJ 2447] 별 찍기 - 10/G5
  RecursiveFunction/BOJ2447/README.md
  RecursiveFunction/BOJ2447/eunjin.py
Labels: 재귀함수

#6 [BOJ 2630] 색종이 만들기 / S2
  RecursiveFunction/BOJ2630/README.md
  RecursiveFunction/BOJ2630/eunjin.py
Labels: 재귀함수

#11 [BOJ 4779] 칸토어 집합/S3
  RecursiveFunction/BOJ4779/hyolim.py
Labels: Add, 재귀함수

#10 [BOJ 4779] 칸토어 집합 / S3
  RecursiveFunction/BOJ4779/eunjin.py
Labels: 재귀함수

#14 [BOJ 4779] 칸토어 집합 / S3
  RecursiveFunction/BOJ4779/hyeonji.py
Labels: Add

#16 [BOJ 6603] 로또 / S2
  Combination/BOJ6603/eunjin.py
Labels: 재귀함수, 조합

#15 [BOJ 6603] 로또 / S2
  Combination/BOJ6603/hyeonji.py
Labels: Add

#26 [BOJ 1759] 암호 만들기 / G5
  Combination/BOJ1759/eunjin.py
Labels: 조합

#25 [BOJ1759] 암호/G5
  Combination/BOJ1759/hyolim.py
Labels: Add, 조합

#23 [BOJ 2630] 색종이 만들기 / S2
  RecursiveFunction/BOJ2630/hyeonji.py
Labels: Add, 재귀함수

#24 [BOJ 2447] 별 찍기 - 10 / G5
  RecursiveFunction/BOJ2447/hyeonji.py
Labels: Add, 재귀함수

#29 [BOJ 1759] 암호 만들기 / G5
  Combination/BOJ1759/hyeonji.py
Labels: Add, 조합

#30 [BOJ 10974] 모든 순열 / S3
  Permutation/BOJ10974/eunjin.py
Labels: 순열

#28 [BOJ 9375] 패션왕 신해빈 / S3
  Combination/BOJ9375/README.md
  Combination/BOJ9375/eunjin.py
Labels: 조합

#32 [BOJ 10974] 모든 순열 / S3
  Permutation/BOJ10974/hyeonji.py
Labels: Add, 순열

#34 [BOJ 11650] 좌표 정렬하기 / S5
  Sorting/BOJ11650/eunjin.py
Labels: Add, 정렬

#33 [BOJ 11650] 좌표 정렬하기 / S5
  Sorting/BOJ11650/hyeonji.py
Labels: Add, 정렬

#42 [BOJ 23246] Sport Climbing Combined / S5
  Sorting/BOJ23246/hyeonji.py
Labels: Add, 정렬

#44 [BOJ 11399] ATM / S4
  Sorting/BOJ 11399/README.md
  Sorting/BOJ 11399/hyeonji.py
Labels: Add, 정렬

#45 [BOJ 2503] 숫자 야구 / S3
  BruteForce/BOJ2503/eunjin.py
Labels: Add, 브루트포스

#35 [BOJ 23246] Sport Climbing Combined / S5
  Sorting/BOJ23246/eunjin.py
Labels: Add, 정렬

#46 [BOJ 11399] ATM / S4
  Sorting/BOJ11399/eunjin.py
Labels: Add, 정렬

#48 [BOJ 2503] 숫자 야구 / S3
  BruteForce/BOJ2503/hyeonji.py
Labels: Add, 브루트포스

#50 [BOJ 1182] 부분수열의 합 / S2
  BruteForce/BOJ1182/eunjin.py
Labels: Add, 브루트포스

#53 [BOJ 1065] 한수 / S4
  BruteForce/BOJ1065/eunjin.py
Labels: Add, 브루트포스

#31 [BOJ10974] 모든 순열/S3
  Permutation/BOJ10974/hyolim.py
Labels: Add, 순열

#47 [BOJ23246] Sport Climbing Combined/S5
  Sorting/BOJ23246/hyolim.py
Labels: Add, 정렬

#49 [BOJ 1182] 부분수열의 합 / S2
  BruteForce/BOJ1182/hyeonji.py
Labels: Add, 브루트포스

#51 [BOJ 1342] 행운의 문자열 / S1
  BruteForce/BOJ1342/eunjin.py
Labels: Add, 브루트포스

#58 [BOJ 14888] 연산자 끼워넣기 / S1
  BruteForce/BOJ14888/eunjin.py
Labels: Add, 브루트포스

#55 [BOJ2503] 숫자야구
  BruteForce/BOJ2503/hyolim.py
Labels: Add, 브루트포스

#59 [BOJ1182] 부분수열의 합/S2
  BruteForce/BOJ1182/hyolim.py
Labels: Add, 브루트포스

#60 [BOJ1342] 행운의 문자열
  BruteForce/BOJ1342/hyolim.py
Labels: Add, 브루트포스

#61 [BOJ 1342] 행운의 문자열 / S1
  BruteForce/BOJ1342/hyeonji.py
Labels: Add, 브루트포스

#54 [BOJ 1065] 한수 / S4
  BruteForce/BOJ1065/hyeonji.py
Labels: Add, 브루트포스

#62 [BOJ 14888] 연산자 끼워넣기 / S1
  BruteForce/BOJ14888/hyeonji.py
Labels: Add, 브루트포스

#68 [BOJ 1026] 보물 / S4
  Greedy/BOJ1026/eunjin.py
Labels: Add, ⭐️ pick, 그리디

#70 [BOJ 5585] 거스름돈 / B2
  Greedy/BOJ5585/hyeonji.py
Labels: Add, ⭐️ pick, 그리디

#73 [BOJ5585] 거스름돈/B2
  Greedy/BOJ5585/hyolim.py
Labels: Add, ⭐️ pick, 그리디

#74 [BOJ1026] 보물/S4
  Greedy/BOJ1026/hyolim.py
Labels: Add, ⭐️ pick, 그리디

#69 [BOJ 14889] 스타트와 링크 / S1
  BruteForce/BOJ14889/hyeonji.py
Labels: Add, 브루트포스

#71 [BOJ 1026] 보물 / S4
  Greedy/BOJ1026/hyeonji.py
Labels: Add, ⭐️ pick, 그리디

#72 [BOJ 11047] 동전 0 / S4
  Greedy/BOJ11047/hyeonji.py
Labels: Add, 그리디

#80 [BOJ2447] 별 찍기-10/G4
  RecursiveFunction/BOJ2447/hyolim.py
Labels: Add, 재귀함수

#81 [BOJ2630] 색종이 만들기/S2
  RecursiveFunction/BOJ2630/hyolim.py
Labels: Add, 재귀함수

#86 그리디 : [BOJ 1461] 도서관 / G4
  Greedy/BOJ1461/eunjin.py
Labels: Add, ⭐️ pick, 그리디

#87 [BOJ 1461] 도서관 / G4
  .DS_Store
  Greedy/BOJ1461/hyolim.py
Labels: Add, 정렬, ⭐️ pick, 그리디

#109 [BOJ 1541] 잃어버린 괄호 / S2
  Greedy/BOJ1541/hyeonji.py
Labels: Add, 그리디

#110 그리디 : [BOJ 2217] 로프 / S4
  Greedy/BOJ2217/hyeonji.py
Labels: Add, 그리디

#118 [BOJ 1461] 도서관 / G4
  Greedy/BOJ1461/hyeonji.py
Labels: Add, ⭐️ pick, 그리디

#119 [BOJ 1149] RGB거리 / S1
  DP/BOJ1149/hyeonji.py
Labels: Add, ⭐️ pick, 다이나믹프로그래밍

#18 [BOJ 1010] 다리놓기 / S5
  Combination/BOJ1010/README.md
  Combination/BOJ1010/eunjin.py
Labels: 조합

#67 [BOJ 11047] 동전 0 / S4
  Greedy/BOJ11047/eunjin.py
Labels: Add, 그리디

#76 [BOJ 1541] 잃어버린 괄호 / S2
  Greedy/BOJ1541/eunjin.py
Labels: Add, 그리디

#78 [BOJ 2217] 로프 / S4
  Greedy/BOJ2217/eunjin.py
Labels: Add, 그리디

#89 [BOJ 1149] RGB거리 / S1
  DP/BOJ1149/eunjin.py
Labels: Add, ⭐️ pick, 다이나믹프로그래밍

#90 [BOJ 11053] 가장 긴 증가하는 부분 수열 / S2
  DP/BOJ11053/eunjin.py
Labels: Add, ⭐️ pick, 다이나믹프로그래밍

#101 [BOJ 2579] 계단 오르기 / S3
  DP/BOJ 2579/eunjin.py
Labels: Add, 다이나믹프로그래밍

#103 [BOJ 9095] 1, 2, 3 더하기 / S3
  DP/BOJ9095/eunjin.py
Labels: Add, 다이나믹프로그래밍

#108 [BOJ 2775] 연속합 / S2
  DP/BOJ1912/eunjin.py
Labels: Add, 다이나믹프로그래밍

#114 [BOJ 2512] 예산 / S2
  BinarySearch/BOJ2512/eunjin.py
Labels: Add, 이분탐색

#115 [BOJ 10815] 숫자 카드 / S5
  BinarySearch/BOJ10815/eunjin.py
Labels: Add, 이분탐색

#127 [BOJ 2343] 기타 레슨 / S1
  ParametricSearch/BOJ2343/eunjin.py
Labels: Add, 파라매트릭 서치

#131 [BOJ 16401] 과자 나눠주기 / S2
  ParametricSearch/BOJ16401/eunjin.py
Labels: Add, 파라매트릭 서치

#133 [BOJ 2470] 두 용액 / G5
  TwoPointers/BOJ2470/eunjin.py
Labels: Add, 투포인터
