Repository CTStudyGroup/BOJ, pull requests merged in 2024-11, with the labels that each got.

#169 241106: BOJ 7569, BOJ 1181
  _eunjin/eunjin_1181.py
  _eunjin/eunjin_7569.py
Labels: Add, 정렬, dfs & bfs

#170 241106
  _hyeonji/BOJ1181
  _hyeonji/BOJ7569
Labels: Add, 정렬, dfs & bfs

#174 241107: BOJ 1436, BOJ 5430
  _eunjin/eunjin_1436.py
  _eunjin/eunjin_5430.py
Labels: 브루트포스, 구현

#177 241108 : [BOJ 1676] 팩토리얼 0의 개수 / S5
  _eunjin/eunjin_1676.py
Labels: 재귀함수

#178 241108 : [BOJ 10026] 적록색약 / G5
  _eunjin/eunjin_10026.py
Labels: dfs & bfs

#173 241107 : [BOJ 1436] 영화감독 숌 / S5
  _hyeonji/hyeonji_1436.py
  _hyeonji/hyeonji_1676.py
Labels: Add

#180 241108 : [BOJ 10026] 적록색약 / G5
  _hyeonji/hyeonji_10026.py
Labels: dfs & bfs

#183 241111 : [BOJ 2751] 수 정렬하기 2 / S5
  _eunjin/eunjin_2751.py
Labels: 정렬

#198 [Add] eunjin_10814.py
  _eunjin/eunjin_10814.py
Labels: 정렬

#199 241114 : [BOJ 2133] 타일 채우기 / G4
  _eunjin/eunjin_2133.py
Labels: 다이나믹프로그래밍

#216 241119 : [BOJ 10773] 제로 / S4
  _eunjin/eunjin_10773.py
Labels: 스택/큐

#217 241119 : [BOJ 14500] 테트로미노 / G4
  _eunjin/eunjin_14500.py
Labels: 브루트포스

#184 241111 : [BOJ 16928] 뱀과 사다리 게임 / G5
  _eunjin/eunjin_16928.py
Labels: dfs & bfs

#188 241112 : [BOJ 1018] 체스판 다시 칠하기 / S4
  _eunjin/eunjin_1018.py
Labels: 브루트포스

#189 241112 : [BOJ 1916] 최소비용 구하기 / G5
  _eunjin/eunjin_1916.py
Labels: 다익스트라

#192 241113 : [BOJ 2839] 설탕 배달 / S4
  _eunjin/eunjin_2839.py
Labels: 그리디

#193 241113 : [BOJ 15486] 퇴사 2 / G5
  _eunjin/eunjin_15486.py
Labels: 다이나믹프로그래밍

#202 241115 : [BOJ 14501] 퇴사 / S3
  _eunjin/eunjin_14501.py
Labels: 다이나믹프로그래밍

#203 241115 : [BOJ 15650] N과 M (2) / S3
  _eunjin/eunjin_15650.py
Labels: 조합

#214 241118 : [BOJ 9012] 괄호 / S4
  _eunjin/eunjin_9012.py
Labels: 문자열

#215 241118 : [BOJ 2096] 내려가기 / G5
  _eunjin/eunjin_2096.py
Labels: 다이나믹프로그래밍

#187 241111 : [BOJ 2751] 수 정렬하기 2 / S5
  _hyeonji/hyeonji_2751.py
Labels: 정렬

#200 241115 : [BOJ 14501] 퇴사 / S3
  _hyeonji/hyeonji_14501.py
Labels: 다이나믹프로그래밍

#201 241115 : [BOJ 15650] N과 M (2) / S3
  _hyeonji/hyeonji_15650.py
Labels: dfs & bfs

#218 241119 : [BOJ 10773] 제로 / S4
  _hyeonji/hyeonji_10773.py
Labels: 스택/큐

#219 241120 : [BOJ 1929] 소수 구하기 / S3
  _eunjin/eunjin_1929.py
Labels: 수학

#221 241120 : [BOJ 1929] 소수 구하기 / S3
  _hyeonji/hyeonji_1929.py
Labels: 구현, 수학

#220 241120 : [BOJ 14940] 쉬운 최단거리 / S1
  _eunjin/eunjin_19490.py
Labels: dfs & bfs

#222 241121 : [BOJ 10816] 숫자 카드 2 / S4
  _eunjin/eunjin_10816.py
Labels: 해시

#223 241121 : [BOJ 11054] 가장 긴 바이토닉 부분 수열 / G4
  _eunjin/eunjin_11054.py
Labels: 다이나믹프로그래밍

#226 241122 : [BOJ 10828] 스택 / S4
  _eunjin/eunjin_10828.py
Labels: 스택/큐

#227 241122 : [BOJ 2580] 스도쿠 / G4
  _eunjin/eunjin_2580.py
Labels: 백트래킹

#232 241129 : [BOJ 1966] 프린터 큐 / S3
  _eunjin/eunjin_1966.py
Labels: 스택/큐

#233 241129 : [BOJ 1987] 알파벳 / G4
  _eunjin/eunjin_1987.py
Labels: dfs & bfs
