Repository CTStudyGroup/BOJ, pull requests merged in 2024-12, with the labels that each got.

#224 241121 : [BOJ 10816] 숫자 카드 2 / S4
  _hyeonji/hyeonji_10816.py
Labels: 해시

#225 241121 : [BOJ 11054] 가장 긴 바이토닉 부분 수열 / G4
  _hyeonji/hyeonji_11054.py
Labels: 다이나믹프로그래밍

#228 241122 : [BOJ 10828] 스택 / S4
  _hyeonji/hyeonji_10828.py
Labels: 스택/큐

#231 241129 : [BOJ 1966] 프린터 큐 / S3
  _hyeonji/hyeonji_1966.py
Labels: 스택/큐

#248 241202 : [BOJ 7568] 덩치 / S5
  _hyeonji/hyeonji_7568.py
Labels: 브루트포스, 구현

#249 241203 : [BOJ 2108] 통계학 / S3
  _hyeonji/hyeonji_2108.py
Labels: 구현

#252 241204 : [BOJ 11866] 요세푸스 문제 0 / S4
  _hyeonji/hyeonji_11866.py
Labels: 스택/큐

#253 241204 : [BOJ 1931] 회의실 배정 / S1
  _hyeonji/hyeonji_1931.py
Labels: 정렬, 그리디

#245 241202 : [BOJ 15686] 치킨 배달 / G5
  _eunjin/eunjin_15686.py
Labels: 브루트포스

#246 241203 : [BOJ 2108] 통계학 / S3
  _eunjin/eunjin_2108.py
Labels: 구현

#247 241203 : [BOJ 17070] 파이프 옮기기 1 / G5
  _eunjin/eunjin_17070.py
Labels: 다이나믹프로그래밍

#250 241204 : [BOJ 11866] 요세푸스 문제 0 / S4
  _eunjin/eunjin_11866.py
Labels: 구현

#251 241204 : [BOJ 1931] 회의실 배정 / S1
  _eunjin/eunjin_1931.py
Labels: 정렬, 그리디

#255 241205 : [BOJ 17219] 비밀번호 찾기 / S4
  _eunjin/eunjin_17219.py
  _eunjin/eunjin_17291.py
Labels: 해시

#263 241206 : [BOJ 1463] 1로 만들기 / S3
  _eunjin/eunjin_1463.py
Labels: 다이나믹프로그래밍

#264 241206 : [BOJ 11660] 구간 합 구하기 5 / S1
  _eunjin/eunjin_11660.py
Labels: 다이나믹프로그래밍

#254 241205 : [BOJ 17219] 비밀번호 찾기 / S4
  _hyeonji/hyeonji_17219.py
Labels: 구현, 해시

#265 241209 : [BOJ 17413] 단어 뒤집기 2 / S3
  _eunjin/eunjin_17413.py
Labels: 스택/큐

#273 241209 : [BOJ 17413] 단어 뒤집기 2 / S3
  _hyeonji/hyeonji_17413.py
Labels: 스택/큐

#266 241209 : [BOJ 2448] 별 찍기 - 11 / G4
  _eunjin/eunjin_2448.py
Labels: 재귀함수

#271 241210 : [BOJ 1449] 수리공 항승 / S3
  _eunjin/eunjin_1449.py
Labels: 그리디

#272 241210 : [BOJ 9465] 스티커 / S1
  _eunjin/eunjin_9465.py
Labels: 다이나믹프로그래밍

#275 241211 : [BOJ 1057] 토너먼트 / S4
  _eunjin/eunjin_1057.py
Labels: 구현

#276 241211 : [BOJ 1629] 곱셈 / S1
  _eunjin/eunjin_1629.py
Labels: 수학

#274 241210 : [BOJ 1449] 수리공 항승 / S3
  _hyeonji/hyeonji_1449.py
Labels: 정렬, 구현

#277 241212 : [BOJ 18110] solved.ac / S4
  _eunjin/eunjin_18110.py
Labels: 정렬, 구현

#278 241212 : [BOJ 2206] 벽 부수고 이동하기 / G3
  _eunjin/eunjin_2206.py
Labels: dfs & bfs

#279 241213 : [BOJ 1969] DNA / S4
  _eunjin/eunjin_1969.py
Labels: 구현, 문자열

#280 241213 : [BOJ 11444] 피보나치 수 6 / G2
  _eunjin/eunjin_11444.py
Labels: 다이나믹프로그래밍, 수학

#288 241217 : [BOJ 2578] 빙고 / S4
  _eunjin/eunjin_2578.py
Labels: 구현

#289 241217 : [BOJ 30805] 사전 순 최대 공통 부분 수열 / G4
  _eunjin/eunjin_30805.py
Labels: 그리디
