Repository CTStudyGroup/BOJ, pull requests merged in 2025-01, with the labels that each got.

#290 241216 : [BOJ 11501] 주식 / S2
  _hyeonji/hyeonji_11501.py
Labels: 그리디

#291 241217 : [BOJ 2578] 빙고 / S4
  _hyeonji/hyeonji_2578.py
Labels: 구현, 시뮬레이션

#292 241217 : [BOJ 30805] 사전 순 최대 공통 부분 수열 / G4
  _hyeonji/hyeonji_30805.py
Labels: 구현

#293 250106 : [BOJ 1058] 친구 / S2
  _eunjin/eunjin_1058.py
Labels: 브루트포스

#294 250106 : [BOJ 1932] 정수 삼각형 / S1
  _eunjin/eunjin_1932.py
Labels: 다이나믹프로그래밍

#295 250106 : [BOJ 1753] 최단경로 / G4
  Dijkstra/BOJ1753/.DS_Store
  Dijkstra/BOJ1753/hyolim
  Dijkstra/BOJ1753/hyolim.c++
Labels: ✅ Add, 다익스트라

#296 250106: [BOJ 1504] 특별한 최단 경로 / G4
  Dijkstra/BOJ1504/hyolim
  Dijkstra/BOJ1504/hyolim.c++
Labels: ✅ Add, 다익스트라

#299 250107 : [BOJ 10973] 이전 순열 / S3
  _eunjin/eunjin_10973.py
Labels: 구현

#300 250107 : [BOJ 1918] 후위 표기식 / G2
  _eunjin/eunjin_1918.py
Labels: 스택/큐

#304 250108 : [BOJ 10157] 자리배정 / S3
  _eunjin/eunjin_10157.py
Labels: 브루트포스

#305 250108 : [BOJ 1967] 트리의 지름 / G4
  _eunjin/eunjin_1967.py
Labels: dfs & bfs

#308 250109 : [BOJ 18310] 안테나 / S3
  _eunjin/eunjin_18310.py
Labels: 정렬

#309 250109 : [BOJ 9935] 문자열 폭발 / G4
  _eunjin/eunjin_9935.py
Labels: 스택/큐

#312 250110 : [BOJ 11508] 2+1 세일 / S4
  _eunjin/eunjin_11508.py
Labels: 그리디

#313 250110 : [BOJ 2467] 용액 / G5
  _eunjin/eunjin_2467.py
Labels: 투포인터

#301 250107 : [BOJ 10973] 이전 순열 / S3
  .DS_Store
  Combination/BOJ10973/hyolim
  Combination/BOJ10973/hyolim.c++
Labels: ✅ Add

#318 250113 : [BOJ 12789] 도키도키 간식드리미 / S3
  _eunjin/eunjin_12789.py
Labels: 스택/큐

#317 250113: [BOJ 1874] 스택 수열 / S2
  _eunjin/eunjin_1874.py
Labels: 스택/큐

#320 250113 : [BOJ 10836] 여왕벌 / G3
  _eunjin/eunjin_10836.py
Labels: 구현

#321 250113 : [BOJ 12789] 도키도키 간식드리미 / S3
  _hyolim/12789_도키도키간식드리미
  _hyolim/12789_도키도키간식드리미.cpp
Labels: 스택/큐

#322 250113 : [BOJ 1874] 스택 수열 / S2
  _hyolim/1874_스택수열
  _hyolim/1874_스택수열.c++
Labels: 스택/큐

#330 250114 : [BOJ 14499] 주사위 굴리기 / G4
  _eunjin/eunjin_14499.py
Labels: 구현

#328 250114 : [BOJ 1744] 수 묶기 / G4
  _eunjin/eunjin_1744.py
Labels: 그리디

#327 250114 : [BOJ 1541] 잃어버린 괄호 / S2
  _eunjin/eunjin_1541.py
Labels: 그리디

#326 250114 : [BOJ 14499] 주사위 굴리기 / G4
  _hyolim/10836_여왕벌
  _hyolim/12789_도키도키간식드리미
  _hyolim/14499_주사위굴리기.c++
  _hyolim/1874_스택수열
Labels: 구현

#336 250115 : [BOJ 2240] 자두나무 / G5
  _eunjin/eunjin_2240.py
Labels: 다이나믹프로그래밍

#335 250115 : [BOJ 10844] 쉬운 계단 수 / S1
  _eunjin/eunjin_10844.py
Labels: 다이나믹프로그래밍

#338 250115 : [BOJ 10844] 쉬운 계단 수 / S1
  _hyolim/10844_쉬운계단수.c++
Labels: 다이나믹프로그래밍

#339 250115 : [BOJ 2240] 자두나무 / G5
  _hyolim/2240_자두나무.c++
Labels: 다이나믹프로그래밍

#337 250115 : [BOJ 17780] 새로운 게임 / G2
  _eunjin/eunjin_17780.py
Labels: 구현

#344 250117 : [BOJ 17829] 222-풀링 / S2
  _eunjin/eunjin_17829.py
Labels: 재귀함수, 구현

#345 250117 : [BOJ 2448] 별 찍기 / G4
  _eunjin/eunjin_2448_2.py
Labels: 재귀함수

#348 250117 : [BOJ 2448] 별찍기 / G4
  _hyolim/2448_별찍기.c++
Labels: 재귀함수

#346 250117 : [BOJ 18808] 스티커 붙이기 / G3
  _eunjin/eunjin_18808.py
Labels: 구현

#349 250118 : [BOJ 18808] 스티커 붙이기 / G3
  _hyolim/18808_스티커붙이기.c++
Labels: 구현

#354 250112 : [BOJ 5567] 결혼식 / S2
  _eunjin/eunjin_5567.py
Labels: dfs & bfs

#353 250120 : [BOJ 5567] 결혼식 / S2
  _hyolim/5567_결혼식.c++
Labels: 그래프

#355 250120 : [BOJ 1043] 거짓말 / G4
  _eunjin/eunjin_1043.py
Labels: dfs & bfs

#356 250120 : [BOJ 1043] 거짓말 / G4
  _hyolim/1043_거짓말.c++
Labels: 그래프

#357 250120 : [BOJ 2239] 스도쿠 / G4
  _eunjin/eunjin_2239.py
Labels: 구현, 백트래킹

#358 250129 : [BOJ 2239] 스토쿠/G4
  _hyolim/2239_스도쿠.c++
Labels: 재귀함수, 구현, 백트래킹

#363 BFS : [BOJ 7562] 나이트의 이동 / S1
  _eunjin/eunjin_7562.py
Labels: dfs & bfs

#368 구현 : [BOJ 14503] 로봇 청소기 / G5
  _eunjin/eunjin_14503.py
Labels: 구현

#365 250112 : [BOJ 7562] 나이트의 이동 / S1
  _hyolim/7562_나이트의이동.c++
Labels: ✅ Add, dfs & bfs

#366 250112 : [BOJ 5427] 불 / G4
  _hyolim/5427_불.c++
Labels: ✅ Add, dfs & bfs

#369 250121 : [BOJ 1004] 어린왕자 / S3
  _hyolim/1004_어린왕자.c++
Labels: ✅ Add, 기하

#373 250122 : [BOJ 2583] 영역 구하기 / S1
  _eunjin/eunjin_2583.py
Labels: dfs & bfs

#375 250122 : [BOJ 2583] 영역구하기 / S1
  _hyolim/2583_영역구하기.c++
Labels: ✅ Add, dfs & bfs

#380 250124 : [BOJ 1967] 트리의 지름 / G4
  _hyolim/1967_트리의지름.c++
Labels: ✅ Add, dfs & bfs

#376 250122 : [BOJ 17143] 낚시왕 / G1
  _eunjin/eunjin_17143.py
Labels: 구현

#381 250124 : [BOJ 1261] 알고스팟 / G4
  _eunjin/eunjin_1261.py
Labels: dfs & bfs, 다익스트라

#382 250124 : [BOJ 11779] 최소비용 구하기 2 / G3
  _eunjin/eunjin_11779.py
Labels: 다익스트라

#383 250124 : [BOJ 3190] 뱀 / G4
  _eunjin/eunjin_3190.py
Labels: 구현
