Repository CTStudyGroup/BOJ, pull requests merged in 2025-10, with the labels that each got.

#1974 250930 : [BOJ 24481] 알고리즘 수업 - 깊이 우선 탐색 3
  _jaewon/24481.py
Labels: dfs & bfs

#1990 251002 : [BOJ 1544] 사이클 단어
  _jaewon/1544.py
Labels: 투포인터

#1991 250102 : [BOJ 2529] 부등호
  _jaewon/2529.py
Labels: 백트래킹

#1993 251003 [BOJ 9009] 피보나치
  _jaewon/9009.py
Labels: 브루트포스

#1999 251007 [BOJ : 18119] 단어 암기
  _sungyoon/18119.cpp
Labels: 비트마스킹

#2000 251007 [BOJ : 14244] 트리 만들기
  _sungyoon/14244.cpp
Labels: 구현
