Repository CTStudyGroup/BOJ, pull requests merged in 2025-05, with the labels that each got.

#1003 250507 : [BOJ 24480] 알고리즘 수업 - 깊이 우선 탐색 2
  _youn/boj_24480.py
Labels: dfs & bfs, 스택/큐

#1004 250507 : [BOJ 24480] 알고리즘수업-깊이우선탐색2
  _hyolim/24480_알고리즘수업깊이우선탐색2.c++
Labels: dfs & bfs

#1007 250507 : [BOJ 17069] 파이프 옮기기 2
  _hyolim/17069_파이프옮기기.c++
Labels: 다이나믹프로그래밍

#1002 250507 : [BOJ 16719] ZOAC
  _hyolim/16719_ZOAC.c++
Labels: 구현, 문자열

#1006 250507 : [BOJ 17069] 파이프 옮기기 2
  17069.cpp
Labels: 다이나믹프로그래밍

#1005 250507 : [BOJ 24480] 알고리즘수업-깊이우선탐색2
  24480.cpp
Labels: dfs & bfs

#1008 250507 : [BOJ 16719] ZOAC
  _youn/boj_16719.py
Labels: 재귀함수, 구현, 문자열

#1015 250508 : [BOJ 2631] 줄세우기
  _youn/boj_2631.py
Labels: 다이나믹프로그래밍

#1020 250508 : [BOJ 2631] 줄세우기
  2631.cpp
Labels: 다이나믹프로그래밍

#1019 250508 : [BOJ 2229] 조 짜기
  2229.cpp
Labels: 다이나믹프로그래밍

#1021 250509 : [BOJ 13023] ABCDE
  _youn/boj_13023.py
Labels: dfs & bfs

#1023 250509 : [BOJ 12970] AB
  _youn/boj_12970.py
Labels: 그리디

#1013 250508 : [BOJ 2116] 주사위 쌓기
  _hyolim/2116_주사위쌓기.c++
Labels: 재귀함수, 구현

#1022 250509 : [BOJ 13023] ABCDE
  13023.cpp
Labels: dfs & bfs

#1029 250512 : [BOJ 20057] 마법사 상어와 토네이도
  _hyolim/22057_마법사상어와토네이도.c++
Labels: 구현

#1033 250513 : [BOJ 1303] 전쟁 - 전투
  _youn/boj_1303.py
Labels: dfs & bfs

#1034 250513 : [BOJ 5569] 출근 경로
  _youn/boj_5569.py
Labels: 다이나믹프로그래밍

#1036 250513 : [BOJ 17140] 이차원 배열과 연산
  _youn/boj_17140.py
Labels: 구현

#1035 250513 : [BOJ 1303] 전쟁 - 전투
  _sungyoon/1303.cpp
Labels: dfs & bfs

#1037 250513 : [BOJ 17140] 이차원 배열과 연산
  _hyolim/17140_이차원배열과연산.c++
Labels: 구현

#1038 250513 : [BOJ 5569] 출근 경로
  _hyolim/5569_출근경로.c++
Labels: 다이나믹프로그래밍

#1044 250514 : [BOJ 11899] 괄호 끼워넣기
  _hyolim/11899_괄호끼워넣기.c++
Labels: 스택/큐

#1045 250514 : [BOJ 1080] 행렬
  _hyolim/1080_행렬.c++
Labels: 그리디

#1046 250514 : [BOJ 1080] 행렬
  _youn/boj_1080.py
Labels: 그리디

#1042 250514 : [BOJ 11899] 괄호 끼워넣기
  _youn/boj_11899.py
Labels: 문자열

#1043 250514 : [BOJ 1756] 피자 굽기
  _hyolim/1756_피자굽기.c++
Labels: 그리디, 구현

#1054 250515 : [BOJ 21758] 꿀 따기
  _hyolim/21758_꿀따기.c++
Labels: 다이나믹프로그래밍

#1051 250515 : [BOJ 22251] 빌런 호석
  _hyolim/22251_빌런호석.c++
Labels: 재귀함수, 구현

#1055 250515 : [BOJ 22251] 빌런 호석
  _youn/boj_22251.py
Labels: 브루트포스, 구현

#1052 250515 : [BOJ 2852] NBA 농구
  _youn/boj_2852.py
Labels: 구현

#1047 250514 : [BOJ 11899] 괄호 끼워넣기
  _sungyoon/11899.cpp
Labels: 스택/큐

#1053 250515 : [BOJ 21758] 꿀 따기
  _sungyoon/21758.cpp
Labels: 브루트포스, 다이나믹프로그래밍

#1060 250516 : [BOJ 2294] 동전 2
  _eunjin/2294_동전2.py
Labels: 다이나믹프로그래밍

#1061 250516 : [BOJ 20058] 마법사 상어와 파이어스톰
  _eunjin/22058_마법사_상어와_파이어스톰.py
Labels: dfs & bfs, 구현

#1062 250516 : [BOJ 20058] 마법사 상어와 파이어스톰
  _hyolim/20058_마법사상어와파이어스톰.c++
Labels: dfs & bfs, 구현

#1063 250516 : [BOJ 20922] 겹치는 건 싫어
  _hyolim/20922_겹치는건싫어.c++
Labels: 투포인터

#1073 250519 : [BOJ 7511] 소셜 네트워킹 어플리케이션
  _youn/boj_7511.py
Labels: 최소신장트리, 유니온파인드

#1069 250519 : [BOJ 1743] 음식물 피하기
  _youn/boj_1743.py
Labels: dfs & bfs

#1071 250519 : [BOJ 7511] 소셜 네트워킹 어플리케이션
  _eunjin/7511_소설_네트워킹_어플리케이션.py
Labels: 유니온파인드

#1072 250519 : [BOJ 1743] 음식물 피하기
  _eunjin/1743_음식물_피하기.py
Labels: dfs & bfs

#1074 250519 : [BOJ 1743] 음식물 피하기
  _sungyoon/1743.cpp
Labels: dfs & bfs

#1075 250519 : [BOJ 7511] 소셜 네트워킹 어플리케이션
  _sungyoon/7511.cpp
Labels: 유니온파인드

#1076 250519 : [BOJ 1790] 수 이어 쓰기 2
  _sungyoon/1790.cpp
Labels: 구현

#1077 250519 : [BOJ 1790] 수 이어 쓰기 2
  _youn/boj_1790.py
Labels: 이분탐색, 수학

#1083 250520 : [BOJ 18429] 근손실
  _youn/boj_18429.py
Labels: 백트래킹

#1084 250520 : [BOJ 2011] 암호코드
  _hyolim/2011_암호코드.c++
Labels: 다이나믹프로그래밍

#1082 250520 : [BOJ 18429] 근손실
  _hyolim/18429_근손실.c++
Labels: 재귀함수

#1085 250520 : [BOJ 2011] 암호코드
  _youn/boj_2011.py
Labels: 다이나믹프로그래밍

#1081 250520 : [BOJ 18429] 근손실
  _eunjin/18429_근손실.py
Labels: 백트래킹

#1089 250520 : [BOJ 2011] 암호코드
  _eunjin/2011_암호코드.py
Labels: 다이나믹프로그래밍

#1086 250520 : [BOJ 17779] 게리맨더링 2
  _eunjin/17779_게리맨더링2.py
Labels: 브루트포스, 구현

#1090 250520 : [BOJ 17779] 게리맨더링 2
  _hyolim/17779_게리맨더링2.c++
Labels: 구현

#1094 250521 : [BOJ 15990] 1, 2, 3 더하기 5
  _hyolim/15990_1,2,3더하기5.c++
Labels: 다이나믹프로그래밍

#1098 250521 : [BOJ 15990] 1, 2, 3 더하기 5
  _youn/boj_15990.py
Labels: 다이나믹프로그래밍

#1101 250521 : [BOJ 9658] 돌 게임 4
  _youn/boj_9658.py
Labels: 다이나믹프로그래밍

#1100 250521 : [BOJ 16935] 배열 돌리기 3
  _hyolim/16935_배열돌리기3.c++
Labels: 구현

#1095 250521 : [BOJ 9658] 돌 게임 4
  _eunjin/9658_돌게임4.py
Labels: 다이나믹프로그래밍

#1096 250521 : [BOJ 9658] 돌 게임 4
  _hyolim/7658_돌게임.c++
Labels: 다이나믹프로그래밍

#1097 250521 : [BOJ 15990] 1, 2, 3 더하기 5
  _eunjin/15990_1,2,3더하기5.py
Labels: 다이나믹프로그래밍

#1099 250521 : [BOJ 16935] 배열 돌리기 3
  _eunjin/16935_배열_돌리기3.py
Labels: 구현

#1103 250521 : [BOJ 16935] 배열 돌리기 3
  _youn/boj_16935.py
Labels: 구현

#1108 250522 : [BOJ 1788] 피보나치 수의 확장
  _eunjin/1788_피보나치_수의_확장.py
Labels: 다이나믹프로그래밍

#1109 250522 : [BOJ 1788] 피보나치 수의 확장
  _youn/boj_1788.py
Labels: 다이나믹프로그래밍

#1113 250522 : [BOJ 18427] 함께 블록 쌓기
  _youn/boj_18427.py
Labels: 다이나믹프로그래밍

#1111 250522 : [BOJ 18427] 함께 블록 쌓기
  _eunjin/18427_함께_블록_쌓기.py
Labels: 다이나믹프로그래밍

#1114 250522 : [BOJ 18427] 함께 블록 쌓기
  _hyolim/18427_함께블록쌓기.cpp
Labels: 다이나믹프로그래밍

#1110 250522 : [BOJ 1788] 피보나치 수의 확장
  _hyolim/1788_피보나치수의확장.c++
Labels: 다이나믹프로그래밍

#1112 250522 : [BOJ 1451] 직사각형으로 나누기
  _hyolim/1451_직사각형으로나누기.cpp
Labels: 브루트포스, 다이나믹프로그래밍, 구현

#1107 250522 : [BOJ 1788] 피보나치 수의 확장
  _sungyoon/1105.cpp
Labels: 다이나믹프로그래밍

#1119 250523 : [BOJ 1914] 하노이 탑
  _hyolim/1914_하노이탑.c++
Labels: 재귀함수, 수학

#1118 250523 : [BOJ 18222] 투에-모스 문자열
  _youn/boj_18222.py
Labels: 수학

#1125 250526 : [BOJ 24479] 알고리즘 수업 - 깊이 우선 탐색 1
  _youn/boj_24779.py
Labels: dfs & bfs

#1127 250526 : [BOJ 24479] 알고리즘 수업 - 깊이 우선 탐색 1
  _hyolim/24479_알고리즘수업-깊이우선탐색.c++
Labels: dfs & bfs

#1130 250526 : [BOJ 2608] 로마 숫자
  _hyolim/2608_로마숫자.c++
Labels: 구현, 문자열, 해시

#1126 250526 : [BOJ 24479] 알고리즘 수업 - 깊이 우선 탐색 1
  _sungyoon/24479.cpp
Labels: dfs & bfs

#1138 250527 : [BOJ 20437] 문자열 게임 2
  _sungyoon/20437.cpp
Labels: 구현, 슬라이딩윈도우

#1137 250527 : [BOJ 19598] 최소 회의실 개수
  _hyolim/19598_최소회의실개수.c++
Labels: 정렬, 우선순위큐

#1136 250527 : [BOJ 19598] 최소 회의실 개수
  _sungyoon/19598.cpp
Labels: 정렬, 우선순위큐

#1135 250527 : [BOJ 20437] 문자열 게임 2
  _youn/boj_20437.py
Labels: 문자열, 슬라이딩윈도우

#1145 250528 : [BOJ 10025] 게으른 백곰
  _youn/boj_10025.py
Labels: 슬라이딩윈도우

#1146 250528 : [BOJ 17503] 맥주 축제
  _hyolim/17503_게으른백곰.c++
Labels: 정렬, 우선순위큐

#1154 250529 : [BOJ 18290] NM과 K (1)
  _youn/boj_18290.py
Labels: 브루트포스, 백트래킹

#1155 250529 : [BOJ 18290] NM과 K (1)
  _hyolim/18290_NM과K.cpp
Labels: 백트래킹
