Repository CTStudyGroup/BOJ, pull requests merged in 2025-09, with the labels that each got.

#1802 ⭐️ 250901 : [BOJ 2257] 화학식량
  _eunjin/2257_화학식량.py
Labels: 스택/큐

#1800 ⭐️ 250901 : [BOJ 2257] 화학식량
  _sungyoon/2257.cpp
Labels: 스택/큐

#1804 ⭐️ 250901 : [BOJ 14712] 넴모넴모 (Easy)
  _sungyoon/14712.cpp
  _sungyoon/2961.cpp
Labels: 백트래킹

#1819 ⭐️ 250902 : [BOJ 15903] 카드 합체 놀이
  _sungyoon/15903.cpp
Labels: 우선순위큐

#1815 ⭐️ 250902 : [BOJ 2961] 도영이가 만든 맛있는 음식
  _eunjin/2961_도영이가_만든_맛있는_음식.py
Labels: 백트래킹

#1818 ⭐️ 250902 : [BOJ 15903] 카드 합체 놀이
  _eunjin/15903_카드_합체_놀이.py
Labels: 그리디, 우선순위큐

#1803 ⭐️ 250901 : [BOJ 2257] 화학식량
  _jaewon/2257.py
Labels: 스택/큐

#1805 ⭐️ 250901 : [BOJ 2257] 화학식량
  _chongmyoung/2257_화학식량.java
Labels: 스택/큐

#1808 ⭐️ 250901 : [BOJ 14712] 넴모넴모 (Easy)
  _chongmyoung/14712_넴모넴모(Easy).java
Labels: 백트래킹

#1830 ⭐️ 250903 : [BOJ 22856] 트리 순회
  _eunjin/22856_트리_순회.py
Labels: dfs & bfs, 트리

#1831 ⭐️ 250903 : [BOJ 1939] 중량제한
  _eunjin/1939_중량제한.py
Labels: 이분탐색, dfs & bfs

#1839 ⭐️ 250904 : [BOJ 2195] 문자열 복사
  _jaewon/2195.py
Labels: 그리디

#1849 ⭐️ 250905 : [BOJ 3980] 선발 명단
  _jaewon/3980.py
Labels: 백트래킹

#1854 ⭐️ 250905 : [BOJ 3980] 선발 명단
  _sungyoon/13975.cpp
  _sungyoon/1406.cpp
  _sungyoon/19238.cpp
  _sungyoon/21609.cpp
  _sungyoon/21939.cpp
  _sungyoon/2234.py
  _sungyoon/2610.cpp
  _sungyoon/2725.cpp
  _sungyoon/31964.cpp
  _sungyoon/3980.cpp
  _sungyoon/4485.cpp
Labels: 백트래킹

#1886 ⭐️ 250915 : [BOJ 1245] 농장 관리
  _eunjin/1245_농장_관리.py
Labels: dfs & bfs

#1897 ⭐️ 250916 : [BOJ 10819] 차이를 최대로
  _hyunseo/10819.py
Labels: 덱

#1898 ⭐️ 250916 : [BOJ 8983] 사냥꾼
  _jaewon/8983.py
Labels: 정렬

#1903 ⭐️ 250916 : [BOJ 8983] 사냥꾼
  _sungyoon/8983.cpp
Labels: 이분탐색

#1925 ⭐️ 250919 : [BOJ 1080] 행렬
  _eunjin/1080_행렬.py
Labels: 그리디

#1928 ⭐️ 250919 : [BOJ 1080] 행렬
  _sungyoon/1080.cpp
Labels: 그리디

#1937 ⭐️ 250922 : [BOJ 2616] 소형기관차
  _eunjin/2616_소형기관차.py
Labels: 다이나믹프로그래밍, 누적합

#1956 250924 : [BOJ 21276] 계보 복원가 호석
  _eunjin/21276_계보_복원가_호석.py
Labels: 위상정렬

#1949 250924 : [BOJ 9742] 순열
  _sungyoon/9742.cpp
Labels: 백트래킹

#1950 250924 : [BOJ 17352] 여러분의 다리가 되어 드리겠습니다!
  _sungyoon/17352.cpp
Labels: 유니온파인드

#1951 250924 : [BOJ 4889] 안정적인 문자열
  _sungyoon/4889.cpp
Labels: 스택/큐

#1963 250927 : [BOJ 14863] 서울에서 경산까지
  _jaewon/14863.py
  _jaewon/9009.py
Labels: 백트래킹

#1968 250929 : [BOJ 17212] 달나라 토끼를 위한 구매대금 지불 도우미
  _jaewon/17212.py
Labels: 다이나믹프로그래밍

#1960 250925 : [BOJ 2660] 회장뽑기
  _sungyoon/2660.cpp
Labels: 플로이드 워셜

#1976 250930 : [BOJ 13904] 과제
  _sungyoon/13904.cpp
Labels: 정렬, 그리디
