Repository CTStudyGroup/BOJ, pull requests merged in 2025-02, with the labels that each got.

#389 250203 : [BOJ 10971] 외판원 순회2 / S2
  _hyolim/10971_외판원순회2.c++
Labels: 백트래킹

#390 250203 : [BOJ 12100] 2048 (Easy) / G1
  _hyolim/12100_2048.c++
Labels: 구현

#391 250203 : [BOJ 5525] IOIOI / S1
  _hyolim/5525_IOIOI.c++
Labels: ✅ Add, 문자열

#393 250203 : [BOJ 5525] IOIOI / S1
  _eunjin/eunjin_5525.py
Labels: 문자열

#394 250203 : [BOJ 7490] 0 만들기 / G5
  _eunjin/eunjin_7490.py
Labels: 브루트포스, 문자열

#395 250203 : [BOJ 10971] 외판원 순회2 / S2
  _eunjin/eunjin_10971.py
Labels: 백트래킹

#396 250203 : [BOJ 12100] 2048 (Easy) / G1
  _eunjin/eunjin_12100.py
Labels: 구현

#401 250204 : [BOJ 27964] 콰트로치즈피자 / S5
  _eunjin/eunjin_27964.py
Labels: 문자열

#402 250204 : [BOJ 16236] 아기 상어 / G3
  _eunjin/eunjin_16236.py
Labels: 구현

#405 250204 : [BOJ 2805] 나무 자르기 / S2
  _eunjin/eunjin_2805.py
Labels: 이분탐색

#406 250204 : [BOJ 1253] 좋다 / G4
  _eunjin/eunjin_1253.py
Labels: 이분탐색

#403 250204 : [BOJ 16236] 아기 상어 / G3
  _hyolim/16236_아기상어.cpp
Labels: 구현

#404 250204 : [BOJ 27964] 콰트로치즈피자 / S5
  _hyolim/27964_콰트로치즈피자.cpp
Labels: 문자열

#415 250205 : [BOJ 9471] 피사노주기 / S4
  _hyolim/9471_피사노주기.cpp
Labels: 수학

#416 250205 : [BOJ16234] 인구이동 / G4
  _hyolim/16234_인구이동.cpp
Labels: ✅ Add, 구현

#422 250205 : [BOJ 1644] 소수의 연속합 / G3
  _hyolim/1644_소수의연속합.cpp
Labels: 투포인터, 수학

#419 투포인터 : [BOJ 2831] 댄스 파티 / G4
  _eunjin/eunjin_2831.py
Labels: 그리디, 투포인터

#417 250205 : [BOJ 9471] 피사노 주기 / S4
  _eunjin/eunjin_9471.py
Labels: 수학

#418 구현 : [BOJ 16234] 인구 이동 / G4
  _eunjin/eunjin_16234.py
Labels: dfs & bfs, 구현

#421 투포인터 : [BOJ 1644] 소수의 연속합 / G3
  _eunjin/eunjin_1644.py
Labels: 투포인터

#429 구현 : [BOJ 20207] 달력 / G5
  _eunjin/eunjin_20207.py
Labels: 그리디, 구현

#428 250207 : [BOJ 21736] 헌내기는 친구가 필요해 / S2
  _eunjin/eunjin_21736.py
Labels: dfs & bfs

#430 250207 : [BOJ 21736] 헌내기는 친구가 필요해 / S2
  _hyolim/21736_헌내기는친구가필요해.c++
Labels: dfs & bfs

#432 250207 : [BOJ 1141] 접두사 / S1
  _hyolim/1141_접두사.c++
Labels: 정렬, 문자열

#431 250207 : [BOJ 20207] 달력 / G5
  _hyolim/20207_달력.c++
Labels: 구현

#434 정렬 : [BOJ 1141] 접두사 / S1
  _eunjin/eunjin_1141.py
Labels: 정렬, 그리디

#440 250210 : [BOJ 4358] 생태학 / S2
  _eunjin/eunjin_4358.py
Labels: 문자열, 해시

#441 250210 : [BOJ 20301] 반전 요세푸스 / S3
  _eunjin/eunjin_20301.py
Labels: 구현, 덱

#442 DP : [BOJ 10942] 팰린드롬? / G4
  _eunjin/eunjin_10942.py
Labels: 다이나믹프로그래밍

#443 250210 : [BOJ 4358] 생태학 / S2
  _hyolim/4358_생태학.c++
Labels: 구현, 문자열

#444 250210 : [BOJ 20301] 반전 요세푸스 / S3
  _hyolim/20301_반전요세푸스.c++
Labels: 구현

#446 250210 : [BOJ 10942] 팰린드롬? / G4
  _hyolim/10942_팰린드롬.c++
Labels: 다이나믹프로그래밍

#445 구현 : [BOJ 1022] 소용돌이 예쁘게 출력하기 / G3
  _eunjin/eunjin_1022.py
Labels: 구현

#453 Create 1022_소용돌이예쁘게출력하기.c++
  _hyolim/1022_소용돌이예쁘게출력하기.c++
Labels: 구현

#451 250211 : [BOJ 14620] 꽃길 / S2
  _eunjin/eunjin_14620.py
Labels: 브루트포스

#456 250211 : [BOJ 18352] 특정 거리의 도시 찾기 / S2
  _hyolim/18352_특정거리의도시찾기.c++
Labels: 다익스트라

#457 250211 : [BOJ 10835] 카드게임 / G5
  _hyolim/10835_카드게임.c++
Labels: 다이나믹프로그래밍

#452 250211 : [BOJ 18352] 특정 거리의 도시 찾기 / S2
  _eunjin/eunjin_18352.py
Labels: dfs & bfs

#454 250211 : [BOJ 10835] 카드게임 / G5
  _eunjin/eunjin_10835.py
Labels: 다이나믹프로그래밍

#458 구현 : [BOJ 13460] 구슬 탈출 2 / G1
  _eunjin/eunjin_13460.py
Labels: 구현

#464 250212 : [BOJ 15903] 카드 합체 놀이 / S1
  _eunjin/eunjin_15903.py
Labels: 정렬, 그리디

#463 250212 : [BOJ 3986] 좋은 단어 / S4
  _eunjin/eunjin_3986.py
Labels: 스택/큐

#467 250212 : [BOJ 3986] 좋은 단어 / S4
  _hyolim/3986_좋은단어.c++
Labels: 스택/큐

#468 250212 : [BOJ 15903] 카드 합체 놀이 / S1
  _hyolim/15903_카드합체놀이.c++
Labels: 그리디

#465 250212 : [BOJ 6987] 월드컵 / G4
  _eunjin/eunjin_6987.py
Labels: 백트래킹

#469 구현 : [BOJ 14890] 경사로 / G3
  _eunjin/eunjin_14890.py
Labels: 구현

#470 250212 : [BOJ 2987] 월드컵 / G4
  _hyolim/6987_월드컵.c++
Labels: 백트래킹

#476 250214 : [BOJ 12845] 모두의 마블 / S3
  _eunjin/eunjin_12845.py
Labels: 그리디

#478 250214 : [BOJ 19539] 사과나무 / G5
  _eunjin/eunjin_19539.py
Labels: 그리디

#482 250214 : [BOJ 1405] 미친 로봇 / G4
  _eunjin/eunjin_1405.py
Labels: dfs & bfs, 백트래킹

#477 250214 : [BOJ 12845] 모두의 마블 / S3
  _hyolim/12845_모두의마블.c++
Labels: 정렬, 그리디

#479 250214 : [BOJ 19539] 사과나무 / G5
  _hyolim/19539_사과나무.c++
Labels: 그리디, 수학

#480 250214 : [BOJ 14891] 톱니바퀴 / G5
  _hyolim/14891_톱니바퀴.c++
Labels: 구현

#481 250214 : [BOJ 1405] 미친로봇 / G4
  _hyolim/1405_미친로봇.c++
Labels: 수학, 백트래킹

#483 구현 : [BOJ 14891] 톱니바퀴 / G5
  _eunjin/eunjin_14891.py
Labels: 구현, 덱

#488 구현 : [BOJ 2573] 빙산 / G4
  _eunjin/eunjin_2573.py
Labels: dfs & bfs, 구현

#489 250217 : [BOJ 1105] 팔 / S1
  _eunjin/eunjin_1105.py
Labels: 그리디

#490 250217 : [BOJ 11055] 가장 큰 증가하는 부분 수열 / S2
  _eunjin/eunjin_11055.py
Labels: 다이나믹프로그래밍

#498 250224 : [BOJ 2670] 연속부분최대곱 / S4
  _eunjin/eunjin_2670.py
Labels: 다이나믹프로그래밍

#500 250224 : [BOJ 15685] 드래곤커브/G3
  _hyolim/15685_드래곤커브
  _hyolim/15685_드래곤커브.c++
Labels: ✅ Add, 구현

#502 250224 : [BOJ 2670] 연속부분최대곱 / S4
  _hyolim/2670_연속부분최대곱
  _hyolim/2670_연속부분최대곱.c++
Labels: 다이나믹프로그래밍

#503 250224 : [BOJ 9657] 돌게임 / S3
  _hyolim/9657_돌게임3
  _hyolim/9657_돌게임3.c++
Labels: 다이나믹프로그래밍

#504 구현 : [BOJ 15685] 드래곤 커브 / G3
  _eunjin/eunjin_15685.py
Labels: 구현

#499 250224 : [BOJ 1339] 단어 수학 / G4
  _eunjin/eunjin_1339.py
Labels: 그리디

#501 250224 : [BOJ 9657] 돌 게임 3 / S3
  _eunjin/eunjin_9657.py
Labels: 다이나믹프로그래밍

#505 250224 : [BOJ 1339] 단어수학 / G4
  _hyolim/1339_단어수학
  _hyolim/1339_단어수학.c++
Labels: 그리디, 문자열, 해시

#513 250225 : [BOJ 15684] 사다리조작 / G3
  _hyolim/15684_사다리조작
  _hyolim/15684_사다리조작.c++
Labels: 구현, 백트래킹

#515 250225 : [BOJ 2458] 키순서 / G4
  _hyolim/2458_키순서.c++
Labels: dfs & bfs

#514 구현 : [BOJ 15684] 사다리 조작 / G3
  _eunjin/eunjin_15684.py
Labels: 구현, 백트래킹

#511 250225 : [BOJ 10164] 격자상의 경로 / S2
  _eunjin/eunjin_10164.py
Labels: 수학

#510 250225 : [BOJ 2458] 키 순서 / G4
  _eunjin/eunjin_2458.py
Labels: dfs & bfs

#516 250225 : [BOJ 10164] 격자 상 경로 / S2
  _hyolim/10164_격자상의경로.c++
Labels: dfs & bfs

#517 250225 : [BOJ 16472] 고냥이 / G4
  _hyolim/1339_단어수학
  _hyolim/15684_사다리조작
  _hyolim/15685_드래곤커브
  _hyolim/16472_고냥이
  _hyolim/16472_고냥이.c++
  _hyolim/2670_연속부분최대곱
  _hyolim/9657_돌게임3
Labels: 투포인터

#512 250225 : [BOJ 16472] 고냥이 / G4
  _eunjin/eunjin_16472.py
Labels: 투포인터

#524 250226 : [BOJ 14719] 빗물 / G5
  _hyolim/14719_빗물.c++
Labels: 구현

#526 250225 : [BOJ 19941] 햄버거 분배 / S3
  _hyolim/19941_햄버거분배.c++
Labels: 그리디

#527 250226 : [BOJ 16922] 햄버거분배/S3
  _hyolim/16922_햄버거분배.c++
Labels: 조합, 백트래킹

#529 250226 : [BOJ 2589] 보물섬 / G5
  _hyolim/2589_보물 섬.c++
Labels: 브루트포스, dfs & bfs

#528 구현 : [BOJ 14719] 빗물 / G5
  _eunjin/eunjin_14719.py
Labels: 투포인터

#523 250226 : [BOJ 16922] 로마 숫자 만들기 / S3
  _eunjin/eunjin_16922.py
Labels: 백트래킹

#525 250226 : [BOJ 2589] 보물섬 / G5
  _eunjin/eunjin_2589.py
Labels: dfs & bfs

#522 250226 : [BOJ 19941] 햄버거 분배 / S3
  _eunjin/eunjin_19941.py
Labels: 그리디

#539 250228 : [BOJ 1213] 팰린드롬 만들기 / S3
  _hyolim/1213_팰린드롬만들기.c++
Labels: 정렬, 문자열

#540 250228 : [BOJ 28215] 대피소 / S4
  _hyolim/28215_대피소.c++
Labels: 조합, 구현
