Repository CTStudyGroup/BOJ, pull requests merged in 2025-08, with the labels that each got.

#1526 250801 : [BOJ 16940] BFS 스페셜 저지
  _sungyoon/16940.cpp
Labels: dfs & bfs

#1538 250804 : [BOJ 18222] 투에-모스 문자열
  _eunjin/18222_투에-모스_문자열.py
Labels: 재귀함수, 분할정복

#1541 250804 : [BOJ 17822] 원판 돌리기
  _eunjin/17822_원판_돌리기.py
Labels: 구현, 시뮬레이션

#1536 250804 : [BOJ 11497] 통나무 건너뛰기
  _sungyoon/11497.cpp
Labels: 그리디, 우선순위큐

#1539 250804 : [BOJ 18222] 투에-모스 문자열
  _sungyoon/18222.cpp
Labels: 재귀함수

#1546 250805 : [BOJ 16562] 친구비
  _eunjin/16562_친구비.py
Labels: dfs & bfs

#1547 250805 : [BOJ 15961] 회전 초밥
  _eunjin/15961_회전_초밥.py
Labels: 슬라이딩윈도우

#1549 250805 : [BOJ 11559] Puyo Puyo
  _eunjin/11559_Puyo_Puyo.py
Labels: dfs & bfs, 구현, 시뮬레이션

#1545 250805 : [BOJ 16562] 친구비
  _sungyoon/16562.cpp
Labels: 유니온파인드

#1548 250805 : [BOJ 11559] Puyo Puyo
  _sungyoon/11559.cpp
Labels: dfs & bfs, 구현

#1553 250806 : [BOJ 5464] 주차장
  _eunjin/5464_주차장.py
Labels: 스택/큐

#1555 250806 : [BOJ 16929] Two Dots
  _eunjin/16929_Two_Dots.py
Labels: dfs & bfs

#1556 250806 : [BOJ 5464] 주차장
  _hyunseo/5464.py
Labels: 스택/큐

#1554 250806 : [BOJ 16929] Two Dots
  _hyunseo/16929.py
Labels: dfs & bfs

#1567 250807 : [BOJ 9466] 텀 프로젝트
  _eunjin/9466_텀_프로젝트.py
Labels: dfs & bfs

#1574 250808 : [BOJ 20364] 부동산 다툼
  _eunjin/20364_부동산_다툼.py
Labels: 트리

#1575 250808 : [BOJ 2234] 성곽
  _eunjin/2234_성곽.py
Labels: dfs & bfs, 비트마스킹

#1581 250808 : [BOJ 2234] 성곽
  _jaewon/2234.py
Labels: dfs & bfs

#1576 250808 : [BOJ 20364] 부동산 다툼
  _jaewon/20364.py
  _jaewon/2234.py
Labels: 트리

#1582 250808 : [BOJ 20364] 부동산 다툼
  _sungyoon/20364.cpp
Labels: 구현

#1583 250808 : [BOJ 2234] 성곽
  _sungyoon/2234.cpp
Labels: dfs & bfs, 비트마스킹

#1591 ⚡️ 250811 : [BOJ 25381] ABBC
  _eunjin/25381_ABBC.py
Labels: 그리디, 스택/큐

#1597 ⭐️ 250811 : [BOJ 10216] Count Circle Groups
  _eunjin/10216_Count_Circle_Groups_(2).py
Labels: dfs & bfs

#1595 ⚡️ 250811 : [BOJ 14442] 벽 부수고 이동하기 2
  _eunjin/14442_벽_부수고_이동하기_2.py
Labels: dfs & bfs

#1600 ⚡️ 250811 : [BOJ 2638] 치즈
  _eunjin/2638_치즈.py
Labels: dfs & bfs, 구현

#1592 ⭐️ 250811 : [BOJ 10216] Count Circle Groups
  _sungyoon/10216.cpp
  _sungyoon/14442.cpp
Labels: 유니온파인드

#1598 ⚡️ 250811 : [BOJ 25381] ABBC
  _sungyoon/25381.cpp
Labels: 스택/큐

#1594 ⭐️ 250811 : [BOJ 16974] 레벨 햄버거
  _jaewon/16974.py
Labels: 분할정복

#1601 ⭐️ 250811 : [BOJ 10216] Count Circle Groups
  _jaewon/10216.py
Labels: dfs & bfs

#1599 ⭐️ 250811 : [BOJ 10216] Count Circle Groups
  _hyejoon/10216.py
Labels: 유니온파인드

#1611 ⭐️ 250812 : [BOJ 1189] 컴백홈
  _eunjin/1189_컴백홉.py
Labels: dfs & bfs, 백트래킹

#1610 ⭐️ 250812 : [BOJ 18430] 무기 공학
  _eunjin/18430_무기_공학.py
Labels: 백트래킹

#1613 ⭐️ 250812 : [BOJ 18430] 무기 공학
  _jaewon/18430.py
Labels: 백트래킹

#1614 ⚡️ 250812 : [BOJ 13459] 구슬 탈출
  _eunjin/14567_선수과목.py
Labels: dfs & bfs, 구현, 시뮬레이션

#1609 ⭐️ 250812 : [BOJ 1189] 컴백홈
  _jaewon/1189.py
Labels: dfs & bfs

#1608 ⚡️ 250812 : [BOJ 14567] 선수과목 (Prerequisite)
  _sungyoon/14567.cpp
Labels: 위상정렬

#1612 ⭐️ 250812 : [BOJ 20058] 마법사 상어와 파이어스톰
  _sungyoon/20058.cpp
Labels: dfs & bfs, 구현

#1623 ⚡️ 250813 : [BOJ 15644] 구슬 탈출 3
  .github/CODEOWNERS
  .github/workflows/pr-action.yml
  README.md
  _eunjin/15644_구슬_탈출_3.py
Labels: dfs & bfs, 구현, 시뮬레이션

#1629 ⭐️ 250814 : [BOJ 5639] 이진 검색 트리
  _eunjin/18500_미네랄_2.py
  _eunjin/5639_이진_검색_트리.py
Labels: 재귀함수, dfs & bfs, 트리

#1633 ⚡️ 250814 : [BOJ 18500] 미네랄 2
  _eunjin/18500_미네랄2.py
Labels: dfs & bfs, 구현, 시뮬레이션

#1630 ⭐️ 250814 : [BOJ 21314] 민겸 수
  _jaewon/21314.py
  _jaewon/5639.py
Labels: 백트래킹, 누적합

#1632 ⭐️ 250814 : [BOJ 5639] 이진 검색 트리
  _jaewon/5639.py
Labels: 스택/큐, 트리

#1645 ⭐️ 250815 : [BOJ 14620] 꽃길
  _sungyoon/14620.cpp
Labels: 백트래킹

#1642 ⚡️ 250815 : [BOJ 14395] 4연산
  _eunjin/14395_4연산.py
Labels: dfs & bfs

#1643 ⭐️ 250815 : [BOJ 14620] 꽃길
  _eunjin/14620_꽃길.py
Labels: 브루트포스, 백트래킹

#1641 ⭐️ 250815 : [BOJ 14620] 꽃길
  _jaewon/14620.py
Labels: 백트래킹

#1644 ⭐️ 250815 : [BOJ 2785] 체인
  _jaewon/2785.py
Labels: 구현

#1662 ⚡️ 250818 : [BOJ 21758] 꿀 따기
  _eunjin/21758_꿀_따기.py
Labels: 그리디, 누적합

#1665 ⭐️ 250818 : [BOJ 14888] 연산자 끼워넣기
  _chongmyoung/14888.java
Labels: 백트래킹

#1666 ⭐️ 250818 : [BOJ 3078] 좋은 친구
  _sungyoon/3078.cpp
Labels: 스택/큐

#1680 ⭐️ 250819 : [BOJ 9177] 단어 섞기
  _sungyoon/9177i.cpp
Labels: 다이나믹프로그래밍, dfs & bfs

#1681 ⚡️ 250818 : [BOJ 2931] 가스관
  _sungyoon/2931i.cpp
Labels: 구현, 시뮬레이션

#1675 ⭐️ 250819 : [BOJ 1411] 비슷한 단어
  _jaewon/1411.py
Labels: 브루트포스

#1689 ⭐️ 250820 : [BOJ 20500] Ezreal 여눈부터 가네 ㅈㅈ
  _eunjin/20500_Ezreal_여눈부터_가네_ㅈㅈ.py
Labels: 다이나믹프로그래밍

#1687 ⭐️ 250820 : [BOJ 1706] 크로스워드
  _jaewon/1706.py
Labels: 브루트포스, 스택/큐

#1698 ⭐️ 250821 : [BOJ 13702] 이상한 술집
  _jaewon/13702.py
Labels: 이분탐색

#1697 ⭐️ 250821 : [BOJ 19598] 최소 회의실 개수
  _eunjin/19598_최소_회의실_개수.py
Labels: 정렬, 우선순위큐

#1699 ⭐️ 250821 : [BOJ 13702] 이상한 술집
  _eunjin/13702_이상한_술집.py
Labels: 이분탐색

#1712 ⭐️ 250822 : [BOJ 16472] 고냥이
  _sungyoon/1662.cpp
Labels: 투포인터, 해시

#1713 ⭐️ 250822 : [BOJ 1662] 압축
  _jaewon/1662.py
Labels: 스택/큐

#1715 ⭐️ 250822 : [BOJ 16472] 고냥이
  _hyunseo/16472.py
Labels: 슬라이딩윈도우

#1716 ⭐️ 250822 : [BOJ 16472] 고냥이
  _jaewon/16472.py
Labels: 투포인터

#1717 ⭐️ 250822 : [BOJ 1662] 압축
  _chongmyoung/1662_압축.java
Labels: 스택/큐

#1718 ⭐️ 250822 : [BOJ 18500] 미네랄 2
  _hyunseo/18500.py
Labels: 구현

#1730 ⭐️ 250825 : [BOJ 6443] 애너그램
  _eunjin/6443_애너그램_2.py
Labels: 백트래킹

#1728 ⭐️ 250825 : [BOJ 18223] 민준이와 마산 그리고 건우
  _sungyoon/18223.cpp
Labels: 다익스트라

#1747 ⭐️ 250826 : [BOJ 18116] 로봇 조립
  _sungyoon/18116.cpp
Labels: 유니온파인드

#1745 ⚡️ 250826 : [BOJ 19638] 센티와 마법의 뿅망치
  _sungyoon/19638.cpp
Labels: 우선순위큐

#1744 ⭐️ 250826 : [BOJ 14284] 간선 이어가기 2
  _eunjin/24284_간선_이어가기_2.py
Labels: 다익스트라

#1748 ⭐️ 250826 : [BOJ 18116] 로봇 조립
  _eunjin/18116_로봇_조립.py
Labels: 유니온파인드

#1732 ⭐️ 250825 : [BOJ 18223] 민준이와 마산 그리고 건우
  _chongmyoung/18223_민준이와_마산_그리고_건우.java
Labels: 다익스트라

#1746 ⭐️ 250826 : [BOJ 14284] 간선 이어가기 2
  _jaewon/14284.py
Labels: 다익스트라, 우선순위큐

#1760 ⭐️ 250827 : [BOJ 1374] 강의실
  _chongmyoung/1374_강의실.java
Labels: 그리디, 우선순위큐

#1752 ⭐️ 250826 : [BOJ 18116] 로봇 조립
  _hyunseo/18116.py
Labels: 유니온파인드

#1751 ⭐️ 250826 : [BOJ 14284] 간선 이어가기 2
  _chongmyoung/14284_간선_이어가기2.java
Labels: 다익스트라, 우선순위큐

#1761 ⭐️ 250827 : [BOJ 1374] 강의실
  _jaewon/1374.py
Labels: 정렬, 우선순위큐

#1763 ⭐️ 250827 : [BOJ 17143] 낚시왕
  _hyunseo/17143.py
Labels: 구현

#1770 ⭐️ 250828 : [BOJ 16938] 캠프 준비
  _eunjin/16938_캠프_준비.py
Labels: 백트래킹

#1776 ⭐️ 250828 : [BOJ 1660] 캡틴 이다솜
  _eunjin/1660_캡틴_이다솜.py
Labels: 다이나믹프로그래밍

#1774 ⭐️ 250828 : [BOJ 1660] 캡틴 이다솜
  _jaewon/1660.py
Labels: 다이나믹프로그래밍

#1785 ⭐️ 250829 : [BOJ 11277] 2-SAT - 1
  _eunjin/11277_2-SAT-1.py
Labels: 브루트포스, 백트래킹

#1787 ⚡️ 250829 : [BOJ 21610] 마법사 상어와 비바라기
  _eunjin/21610_마법사_상어와_비바라기.py
Labels: 구현, 시뮬레이션

#1790 ⭐️ 250829 : [BOJ 11277] 2-SAT - 1
  _sungyoon/11277.cpp
Labels: 브루트포스, 비트마스킹

#1791 ⚡️ 250829 : [BOJ 1327] 소트 게임
  _sungyoon/1327.cpp
Labels: dfs & bfs, 해시
