Repository CTStudyGroup/BOJ, pull requests merged in 2025-04, with the labels that each got.

#732 ⭐️ 250401 : [BOJ 17086] 아기 상어 2
  _hyolim/17086_아기상어.cpp
Labels: dfs & bfs

#730 ⭐️ 250401 : [BOJ 3019] 테트리스
  _eunjin/eunjin_3019.py
Labels: 브루트포스, 구현

#734 ⭐️ 250401 : [BOJ 3019] 테트리스
  _hyolim/3019_테트리스.cpp
Labels: 구현

#731 ⭐️ 250401 : [BOJ 17086] 아기 상어 2
  _eunjin/eunjin_17086.py
Labels: dfs & bfs

#733 ⭐️ 250401 : [BOJ 17086] 아기 상어 2
  _gilljong/17086.py
Labels: dfs & bfs

#735 ⭐️ 250401 : [BOJ 3019] 테트리스
  _gilljong/3019.py
Labels: 구현

#725 250331 : [BOJ 2877] 4와 7
  _gilljong/2877.py
Labels: 구현, 문자열

#724 250331 : [BOJ 11899] 괄호 끼워넣기
  _gilljong/11899.py
Labels: 구현, 문자열

#736 ⭐️ 250401 : [BOJ 17086] 아기 상어 2
  _sungyoon/17086.cpp
Labels: dfs & bfs

#718 ⭐️ 250328 : [BOJ 14248] 점프 점프
  14248.cpp
Labels: dfs & bfs

#712 250327 : [BOJ 13565] 침투
  13565.cpp
Labels: dfs & bfs

#737 ⭐️ 250401 : [BOJ 3019] 테트리스
  _youn/boj_3019.py
Labels: 구현

#738 ⭐️ 250401 : [BOJ 3019] 테트리스
  _sungyoon/3019.cpp
Labels: 브루트포스, 구현

#739 ⭐️ 250401 : [BOJ 17086] 아기 상어 2
  _youn/boj_17086.py
Labels: dfs & bfs

#744 ⭐️ 250402 : [BOJ 14650] 걷다보니 신천역 삼 (Small)
  _eunjin/eunjin_14650.py
Labels: 브루트포스, 수학

#745 ⭐️ 250402 : [BOJ 17406] 배열 돌리기 4
  _hyolim/17406_배열돌리기.c++
Labels: 구현

#747 ⭐️ 250402 : [BOJ 17406] 배열 돌리기 4
  _eunjin/eunjin_17406.py
Labels: 브루트포스, 구현

#749 ⭐️ 250402 : [BOJ 14650] 걷다보니 신천역 삼 (Small)
  _sungyoon/14650.cpp
Labels: 순열, 백트래킹

#746 ⭐️ 250402 : [BOJ 14650] 걷다보니 신천역 삼 (Small)
  _gilljong/14650.py
Labels: dfs & bfs

#752 SOLVE BOJ Youn 740
  _youn/boj_17406.py
Labels: 구현

#753 ⭐️ 250402 : [BOJ 14650] 걷다보니 신천역 삼 (Small)
  _youn/boj_14650.py
Labels: 순열, 브루트포스

#750 250402 : [BOJ 15991] 1, 2, 3 더하기 6
  _hyolim/15991_1,2,3더하기6.c++
Labels: 다이나믹프로그래밍

#755 ⭐️ 250402 : [BOJ 17406] 배열 돌리기 4
  _sungyoon/17406.cpp
Labels: 구현, 백트래킹

#761 ⭐️ 250403 : [BOJ 2992] 크면서 작은 수
  _gilljong/2992.py
Labels: 순열, 정렬

#763 ⭐️ 250403 : [BOJ 2992] 크면서 작은 수
  _sungyoon/2992.cpp
Labels: 순열, 백트래킹

#762 ⭐️ 250403 : [BOJ 2992] 크면서 작은 수
  _youn/boj_2992.py
Labels: 순열

#760 ⭐️ 250403 : [BOJ 2992] 크면서 작은 수
  _eunjin/eunjin_2992.py
Labels: 브루트포스

#773 ⭐️ 250404 : [BOJ 3184] 양
  _hyolim/3184_양.c++
Labels: dfs & bfs

#771 ⭐️ 250404 : [BOJ 3184] 양
  _gilljong/1783.py
Labels: dfs & bfs

#774 ⭐️ 250404 : [BOJ 23288] 주사위 굴리기 2
  _gilljong/23288.py
Labels: dfs & bfs, 구현

#772 ⭐️ 250404 : [BOJ 3184] 양
  _youn/boj_3184.py
Labels: dfs & bfs

#766 ⭐️ 250403 : [BOJ 17472] 다리 만들기 2
  _eunjin/eunjin_17472.py
Labels: 브루트포스, dfs & bfs, 구현, 최소신장트리

#777 ⭐️ 250404 : [BOJ 23288] 주사위 굴리기 2
  _youn/boj_23288.py
Labels: dfs & bfs, 구현

#775 ⭐️ 250404 : [BOJ 23288] 주사위 굴리기 2
  _hyolim/23288_주사위굴리기2.c++
Labels: dfs & bfs, 구현

#776 ⭐️ 250404 : [BOJ 3184] 양
  _sungyoon/3184.cpp
Labels: dfs & bfs

#778 ⭐️ 250404 : [BOJ 3184] 양
  _eunjin/eunjin_3184.py
Labels: dfs & bfs

#779 ⭐️ 250404 : [BOJ 23288] 주사위 굴리기 2
  _eunjin/eunjin_23288.py
Labels: dfs & bfs, 구현, 시뮬레이션

#786 ⭐️ 250407 : [BOJ 2212] 센서
  _youn/boj_2212.py
Labels: 정렬, 그리디

#784 ⭐️ 250407 : [BOJ 2212] 센서
  _eunjin/eunjin_2212.py
Labels: 정렬, 그리디

#790 ⭐️ 250407 : [BOJ 17825] 주사위 윷놀이
  _eunjin/eunjin_17825.py
Labels: 구현, 백트래킹

#785 ⭐️ 250407 : [BOJ 2212] 센서
  _gilljong/2212.py
Labels: 정렬, 그리디

#789 ⭐️ 250407 : [BOJ 17825] 주사위 윷놀이
  _hyolim/17825_주사위윷놀이.cpp
Labels: 재귀함수, 구현, 백트래킹

#799 ⭐️ 250408 : [BOJ 1283] 단축키 지정
  _hyolim/1283_단축키지정.c++
Labels: 구현, 문자열

#788 250407 : [BOJ 1025] 제곱수 찾기
  _sungyoon/1025.cpp
Labels: 브루트포스, 구현

#791 ⭐️ 250407 : [BOJ 2212] 센서
  _sungyoon/2212.cpp
Labels: 정렬, 그리디

#792 ⭐️ 250407 : [BOJ 17825] 주사위 윷놀이
  _sungyoon/17825.cpp
Labels: 브루트포스, 백트래킹

#798 ⭐️ 250408 : [BOJ 1283] 단축키 지정
  _youn/boj_1283.py
Labels: 구현, 문자열

#800 ⭐️ 250408 : [BOJ 1283] 단축키 지정
  _sungyoon/1283.cpp
Labels: 구현, 문자열, 해시

#797 ⭐️ 250408 : [BOJ 1283] 단축키 지정
  _eunjin/eunjin_1283.py
Labels: 구현, 문자열

#801 ⭐️ 250408 : [BOJ 2469] 사다리 타기
  _eunjin/eunjin_2469.py
Labels: 구현, 문자열

#806 ⭐️ 250408 : [BOJ 2469] 사다리 타기
  _hyolim/2469_사다리타기.cpp
Labels: 구현

#808 ⭐️ 250409 : [BOJ 17952] 과제는 끝나지 않아!
  _hyolim/17952_과제는끝나지않아.cpp
Labels: 스택/큐

#811 ⭐️ 250409 : [BOJ 8972] 미친 아두이노
  _hyolim/8972_미친아두이노.cpp
Labels: 구현, 시뮬레이션

#809 ⭐️ 250409 : [BOJ 17952] 과제는 끝나지 않아!
  _eunjin/eunjin_17952.py
Labels: 스택/큐

#810 ⭐️ 250409 : [BOJ 8972] 미친 아두이노
  _eunjin/eunjin_8972.py
Labels: 구현, 시뮬레이션

#812 ⭐️ 250409 : [BOJ 17952] 과제는 끝나지 않아!
  _gilljong/17952.py
Labels: 구현, 스택/큐

#813 ⭐️ 250409 : [BOJ 8972] 미친 아두이노
  _gilljong/8972.py
Labels: 구현, 시뮬레이션

#814 ⭐️ 250409 : [BOJ 8972] 미친 아두이노
  _sungyoon/8972.cpp
Labels: 구현, 시뮬레이션

#815 250409 : [BOJ 11729] 하노이 탑 이동 순서
  _hyolim/11729_하노이탑이동순서.cpp
Labels: 재귀함수

#821 ⭐️ 250410 : [BOJ 11000] 강의실 배정
  _hyolim/11000_강의실배정.c++
Labels: 정렬, 그리디, 우선순위큐

#820 ⭐️ 250410 : [BOJ 11000] 강의실 배정
  _eunjin/eunjin_11000.py
Labels: 정렬, 그리디, 우선순위큐

#822 ⭐️ 250410 : [BOJ 11000] 강의실 배정
  _sungyoon/11000.cpp
Labels: 정렬, 우선순위큐

#823 ⭐️ 250410 : [BOJ 19237] 어른 상어
  _eunjin/eunjin_19237.py
Labels: 구현, 시뮬레이션

#833 ⭐️ 250410 : [BOJ 19237] 어른 상어
  _hyolim/19237_어른상어.c++
Labels: 구현

#832 ⭐️ 250411 : [BOJ 2012] 등수 매기기
  _hyolim/2012_등수매기기.c++
Labels: 정렬, 그리디

#830 ⭐️ 250411 : [BOJ 21608] 상어 초등학교
  _hyolim/21608_상어초등학교.c++
Labels: 구현

#828 ⭐️ 250411 : [BOJ 2012] 등수 매기기
  _eunjin/eunjin_2012.py
Labels: 정렬, 그리디

#829 ⭐️ 250411 : [BOJ 21608] 상어 초등학교
  _eunjin/eunjin_21608.py
Labels: 구현

#835 250412 : 모의 코딩테스트
  _eunjin/eunjin_11123.py
  _eunjin/eunjin_2422.py
  _eunjin/eunjin_2666.py
  _eunjin/eunjin_3109.py
Labels: 🏆 test

#842 ⭐️ 250414 : [BOJ 2002] 추월
  _eunjin/eunjin_2002.py
Labels: 구현, 해시

#841 ⭐️ 250414 : [BOJ 9207] 페그 솔리테어
  _eunjin/eunjin_9207.py
Labels: 구현, 백트래킹

#852 ⭐️ 250415 : [BOJ 2659] 십자카드 문제
  _hyolim/2659_십자카드문제.c++
Labels: 재귀함수, 정렬

#851 ⭐️ 250415 : [BOJ 1111] IQ Test
  _hyolim/1111_IQTest.c++
Labels: 재귀함수, 구현

#849 ⭐️ 250415 : [BOJ 2659] 십자카드 문제
  _eunjin/eunjin_2659.py
Labels: 정렬, 브루트포스

#853 ⭐️ 250415 : [BOJ 2659] 십자카드 문제
  _sungyoon/2659.cpp
Labels: 브루트포스, 구현

#850 ⭐️ 250415 : [BOJ 1111] IQ Test
  _eunjin/eunjin_1111.py
Labels: 구현, 수학, 많은 조건 분기

#854 250415 : [BOJ 2688] 줄어들지 않아
  _eunjin/eunjin_2688.py
Labels: 다이나믹프로그래밍

#855 250415 : [BOJ 15989] 1, 2, 3 더하기 4
  _eunjin/15989_1,2,3더하기4.py
Labels: 다이나믹프로그래밍

#843 ⭐️ 250414 : [BOJ 2002] 추월
  _hyolim/2002_추월.cpp
Labels: 투포인터

#860 ⭐️ 250416 : [BOJ 9084] 동전
  _eunjin/9084_동전.py
Labels: 다이나믹프로그래밍

#864 250416 : [BOJ 5557] 1학년
  _eunjin/5557_1학년.py
Labels: 다이나믹프로그래밍

#865 250416 : [BOJ 16194] 카드 구매하기 2
  _eunjin/16194_카드구매하기2.py
Labels: 다이나믹프로그래밍

#862 ⭐️ 250416 : [BOJ 20061] 모노미노도미노 2
  _hyolim/20061_모노미노도미노2.c++
Labels: 구현

#863 ⭐️ 250416 : [BOJ 20061] 모노미노도미노 2
  _eunjin/20061_모노미노도미노2.py
Labels: 구현, 시뮬레이션

#861 ⭐️ 250416 : [BOJ 9084] 동전
  _youn/boj_9084.py
Labels: 다이나믹프로그래밍

#844 ⭐️ 250414 : [BOJ 2002] 추월
  _sungyoon/2002.cpp
Labels: 브루트포스, 해시

#872 ⭐️ 250417 : [BOJ 2210] 숫자판 점프
  _eunjin/2210_숫자판_점프.py
Labels: dfs & bfs

#875 250417 : [BOJ 1041] 주사위
  _eunjin/1041_주사위.py
Labels: 그리디

#877 250417 : [BOJ 20529] 가장 가까운 세 사람의 심리적 거리
  _eunjin/20529_가장_가까운_세_사람의_심리적_거리.py
Labels: 백트래킹

#878 ⭐️ 250417 : [BOJ 6086] 최대 유량
  _eunjin/6086_최대_유량.py
Labels: 구현

#876 ⭐️ 250417 : [BOJ 2210] 숫자판 점프
  _sungyoon/2210.cpp
Labels: dfs & bfs

#874 ⭐️ 250417 : [BOJ 2210] 숫자판 점프
  _youn/boj_2210.py
Labels: dfs & bfs

#885 ⭐️ 250418 : [BOJ 15664] N과 M (10)
  _youn/boj_15664.py
Labels: 백트래킹

#883 ⭐️ 250418 : [BOJ 15664] N과 M (10)
  _eunjin/15664_N과_M_10.py
Labels: 백트래킹

#884 ⭐️ 250418 : [BOJ 17281] ⚾
  _eunjin/17281_야구.py
Labels: 구현, 시뮬레이션

#886 ⭐️ 250418 : [BOJ 17281] ⚾
  _youn/boj_17281.py
Labels: 브루트포스, 구현

#900 ⭐️ 250421 : [BOJ 6236] 용돈 관리
  _hyolim/6236_용돈관리.cpp
Labels: 파라매트릭 서치

#894 ⭐️ 250421 : [BOJ 6236] 용돈 관리
  _eunjin/6236_용돈_관리.py
Labels: 이분탐색

#897 ⭐️ 250421 : [BOJ 20164] 홀수 홀릭 호석
  _eunjin/20164_홀수_홀릭_호석.py
Labels: 재귀함수, 구현

#895 ⭐️ 250421 : [BOJ 6236] 용돈 관리
  _youn/boj_6236.py
Labels: 그리디, 이분탐색

#899 ⭐️ 250421 : [BOJ 6236] 용돈 관리
  _sungyoon/6236.cpp
Labels: 이분탐색

#898 ⭐️ 250421 : [BOJ 20164] 홀수 홀릭 호석
  _youn/boj_20164..py
Labels: 재귀함수, 브루트포스, 구현

#873 ⭐️ 250417 : [BOJ 2210] 숫자판 점프
  _hyolim/2210_숫자판점프.c++
Labels: 재귀함수, 브루트포스

#901 ⭐️ 250421 : [BOJ 20164] 홀수 홀릭 호석
  _sungyoon/20164.cpp
Labels: 재귀함수, 브루트포스

#908 250422 : [BOJ 11058] 크리보드
  _hyolim/11058_크리보드.c++
Labels: 다이나믹프로그래밍

#907 250422 : [BOJ 11058] 크리보드
  _youn/boj_11058.py
Labels: 다이나믹프로그래밍

#906 250422 : [BOJ 15662] 톱니바퀴 (2)
  _hyolim/15662_톱니바퀴(2).c++
Labels: 재귀함수, 구현

#909 250422 : [BOJ 11058] 크리보드
  _eunjin/11058_크리보드.py
Labels: 다이나믹프로그래밍

#905 250422 : [BOJ 15662] 톱니바퀴 (2)
  _eunjin/1563_개근상.py
  _eunjin/15662_톱니바퀴_2.py
Labels: 구현, 덱

#916 250423 : [BOJ 24445] 알고리즘 수업 - 너비 우선 탐색 2
  _eunjin/24445_알고리즘수업_너비우선탐색2.py
Labels: dfs & bfs

#917 250423 : [BOJ 24445] 알고리즘 수업 - 너비 우선 탐색 2
  _youn/boj_24445.py
Labels: dfs & bfs

#921 250423 : [BOJ 24445] 알고리즘 수업 - 너비 우선 탐색 2
  _hyolim/24445_알고리즘수업너비우선탐색2.c++
Labels: dfs & bfs

#919 250423 : [BOJ 7682] 틱택토
  _hyolim/7682_틱택토.c++
Labels: 구현

#920 250423 : [BOJ 17845] 수강 과목
  _youn/boj_17845.py
Labels: 다이나믹프로그래밍

#918 250423 : [BOJ 17845] 수강 과목
  _eunjin/17845_수강_과목.py
Labels: 다이나믹프로그래밍

#922 250423 : [BOJ 7682] 틱택토
  _eunjin/7682_틱택토.py
Labels: 구현, 많은 조건 분기

#924 250423 : [BOJ 7682] 틱택토
  _youn/boj_7682.py
Labels: 구현, 많은 조건 분기

#923 250423 : [BOJ 17845] 수강 과목
  _hyolim/17845_수강과목.c++
Labels: 다이나믹프로그래밍

#929 250424 : [BOJ 4811] 알약
  _youn/boj_4811.py
Labels: 다이나믹프로그래밍

#931 250424 : [BOJ 3078] 좋은 친구
  _youn/boj_3078.py
Labels: 슬라이딩윈도우

#932 250424 : [BOJ 3425] 고스택
  _hyolim/3425_고스택.c++
Labels: 구현

#928 250424 : [BOJ 4811] 알약
  _eunjin/4811_알약.py
Labels: 다이나믹프로그래밍

#930 250424 : [BOJ 3078] 좋은 친구
  _eunjin/3078_좋은_친구.py
Labels: 슬라이딩윈도우

#941 250424 : [BOJ 3425] 고스택
  _eunjin/3425_고스택.py
Labels: 구현, 스택/큐

#940 250425 : [BOJ 20056] 마법사 상어와 파이어볼
  _eunjin/20056_마법사_상어와_파이어볼.py
Labels: 구현, 시뮬레이션

#938 250425 : [BOJ 20056] 마법사 상어와 파이어볼
  _hyolim/20056_마법사상어와파이어볼.c++
Labels: 구현

#936 250425 : [BOJ 1051] 숫자 정사각형
  _eunjin/1051_숫자_정사각형.py
Labels: 브루트포스

#942 250425 : [BOJ 1051] 숫자 정사각형
  _hyolim/1051_숫자정사각형.c++
Labels: 그리디

#937 250425 : [BOJ 16174] 점프왕 쩰리 (Large)
  _eunjin/16174_점프왕_쩰리_Large.py
Labels: dfs & bfs

#939 250425 : [BOJ 16174] 점프왕 쩰리 (Large)
  _hyolim/16174_점프왕쩰리.c++
Labels: 다이나믹프로그래밍

#944 250425 : [BOJ 1051] 숫자 정사각형
  _sungyoon/1051.cpp
Labels: 브루트포스

#945 250425 : [BOJ 16174] 점프왕 쩰리 (Large)
  _sungyoon/16174.cpp
Labels: dfs & bfs

#946 250422 : [BOJ 15662] 톱니바퀴 (2)
  _sungyoon/15662.cpp
Labels: 시뮬레이션

#953 250428 : [BOJ 1911] 흙길 보수하기
  _hyolim/1911_흙길보수하기.c++
Labels: 정렬, 그리디

#952 250428 : [BOJ 1911] 흙길 보수하기
  _youn/boj_1911.py
Labels: 그리디

#957 250428 : [BOJ 1245] 농장 관리
  _hyolim/1245_농장관리.cpp
Labels: dfs & bfs

#951 250428 : [BOJ 16926] 배열 돌리기 1
  _hyolim/16926_배열돌리기1.c++
Labels: 구현

#955 250428 : [BOJ 1911] 흙길 보수하기
  _sungyoon/1911.cpp
Labels: 정렬, 그리디

#954 250428 : [BOJ 1245] 농장 관리
  _sungyoon/1245.cpp
Labels: dfs & bfs

#959 250428 : [BOJ 16926] 배열 돌리기 1
  _sungyoon/16926.cpp
Labels: 구현, 시뮬레이션

#958 250428 : [BOJ 16926] 배열 돌리기 1
  _youn/boj_16926.py
Labels: ✅ Add, 구현

#963 250429 : [BOJ 16198] 에너지 모으기
  _youn/boj_16198.py
Labels: 브루트포스, 백트래킹

#967 250429 : [BOJ 2643] 색종이 올려 놓기
  _youn/boj_2643.py
Labels: 정렬, 다이나믹프로그래밍

#964 250429 : [BOJ 10993] 별 찍기 - 18
  _eunjin/10993_별찍기_18.py
Labels: 재귀함수, 구현

#966 250429 : [BOJ 16198] 에너지 모으기
  _eunjin/16198_에너지_모으기.py
Labels: 백트래킹

#970 250429 : [BOJ 2643] 색종이 올려 놓기
  _sungyoon/2643.cpp
Labels: 정렬, 다이나믹프로그래밍

#969 250429 : [BOJ 16198] 에너지 모으기
  _sungyoon/16198.cpp
Labels: 브루트포스, 백트래킹

#965 250429 : [BOJ 10993] 별 찍기 - 18
  _hyolim/10993_별찍기18.c++
Labels: 구현

#968 250429 : [BOJ 2643] 색종이 올려 놓기
  _hyolim/2643_색종이올리기.c++
Labels: 정렬, 다이나믹프로그래밍

#975 250430 : [BOJ 20055] 컨베이어 벨트 위의 로봇
  _hyolim/20055_컨베이어벨트위의로봇.cpp
Labels: 구현, 시뮬레이션
