Repository CTStudyGroup/BOJ, pull requests merged in 2025-07, with the labels that each got.

#1333 250701 : [BOJ 1780] 종이의 개수
  _eunjin/1780_종이의_개수.py
Labels: 재귀함수, 분할정복

#1349 250702 : [BOJ 1406] 에디터
  1406.cpp
Labels: 연결리스트

#1347 250702 : [BOJ 2610] 회의준비
  _eunjin/2610_회의준비.py
Labels: dfs & bfs

#1355 250703 : [BOJ 2725] 보이는 점의 개수
  _eunjin/2725_보이는_점의_개수.py
Labels: 수학, 누적합

#1357 250703 : [BOJ 2725] 보이는 점의 개수
  2725.cpp
Labels: 다이나믹프로그래밍

#1351 250702 : [BOJ 19238] 스타트 택시
  19238.cpp
Labels: dfs & bfs, 시뮬레이션

#1358 250703 : [BOJ 21609] 상어 중학교
  _eunjin/21609_상어_중학교.py
Labels: dfs & bfs, 구현, 시뮬레이션

#1367 250704 : [BOJ 31964] 반품 회수
  _sanghoon/_sanghoon/src/반품회수_31964.java
Labels: 그리디

#1365 250704 : [BOJ 4485] 녹색 옷 입은 애가 젤다지?
  4485.cpp
Labels: 다익스트라

#1359 250703 : [BOJ 21609] 상어 중학교
  21609.cpp
Labels: dfs & bfs, 구현, 시뮬레이션

#1379 250707 : [BOJ 19538] 루머
  _sanghoon/_sanghoon/src/루머_19538.java
Labels: dfs & bfs

#1378 250707 : [BOJ 16120] PPAP
  _eunjin/16120_PPAP.py
Labels: 스택/큐

#1380 250707 : [BOJ 19538] 루머
  _eunjin/19538_루머.py
Labels: dfs & bfs

#1382 250707 : [BOJ 17837] 새로운 게임 2
  _eunjin/17837_새로운_게임2.py
Labels: 구현, 스택/큐, 시뮬레이션

#1387 250708 : [BOJ 2885] 초콜릿 식사
  _eunjin/13422_도둑.py
  _eunjin/2885_초콜릿_식사.py
Labels: 그리디

#1373 250704 : [BOJ 12764] 싸지방에 간 준하
  _sungyoon/12764.cpp
Labels: 우선순위큐

#1381 250707 : [BOJ 16120] PPAP
  _sanghoon/_sanghoon/src/PPAP_16120.java
Labels: 스택/큐

#1393 250709 : [BOJ 14267] 회사 문화 1 #1391
  _hyunseo/14267.py
Labels: dfs & bfs

#1402 250710 : [BOJ 2412] 암벽 등반
  _eunjin/2412_암벽_등반.py
Labels: dfs & bfs, 해시

#1401 250710 : [BOJ 2412] 암벽 등반
  _hyunseo/1399.py
Labels: dfs & bfs

#1403 250710 : [BOJ 20166] 문자열 지옥에 빠진 호석
  _hyunseo/20166.py
Labels: dfs & bfs

#1416 250714 : [BOJ 2295] 세 수의 합
  _sungyoon/2295.cpp
Labels: 정렬, 이분탐색

#1437 250716 : [BOJ 2015] 수들의 합 4
  _eunjin/2015_수들의_합_4.py
Labels: 해시, 누적합

#1426 250715 : [BOJ 17503] 맥주 축제
  _sungyoon/17503.cpp
Labels: 정렬, 우선순위큐

#1427 250715 : [BOJ 1992] 쿼드트리
  _sanghoon/_sanghoon/src/쿼드트리_1992.kt
Labels: 분할정복

#1431 250715 : [BOJ 1992] 쿼드트리
  _sungyoon/1922.cpp
Labels: 분할정복

#1446 250717 : [BOJ 2157] 여행
  _eunjin/2157_여행.py
Labels: 다이나믹프로그래밍

#1452 250718 : [BOJ 10597] 순열장난
  _sungyoon/10597.cpp
Labels: 백트래킹

#1454 250719 : 모의 코딩테스트
  _hyunseo/10655.py
Labels: 다이나믹프로그래밍

#1473 250723 : [BOJ 3584] 가장 가까운 공통 조상
  _eunjin/3584_가장_가까운_공통_조상.py
Labels: dfs & bfs

#1478 250724 : [BOJ 4803] 트리
  _eunjin/4803_트리.py
Labels: dfs & bfs, 트리

#1481 250724 : [BOJ 2141] 우체국
  _eunjin/2141_우체국.py
Labels: 그리디

#1488 250725 : [BOJ 11729] 하노이 탑 이동 순서
  _sungyoon/11729.cpp
Labels: 재귀함수

#1486 250725 : [BOJ 11729] 하노이 탑 이동 순서
  _eunjin/11729_하노이_탑_이동_순서.py
Labels: 재귀함수

#1487 250725 : [BOJ 3896] 소수 사이 수열
  _eunjin/3896_소수_사이_수열.py
Labels: 에라토스테네스의 체

#1489 250725 : [BOJ 3987] 보이저 1호
  _eunjin/3987_보이저_1호.py
Labels: 구현, 그래프

#1499 250728 : [BOJ 12849] 본대 산책
  _eunjin/1495_본대_산책.py
Labels: 다이나믹프로그래밍, 그래프

#1505 250729 : [BOJ 12970] AB
  _eunjin/12970_AB.py
Labels: 그리디, 수학

#1509 250729 : [BOJ 1726] 로봇
  _sungyoon/1726.cpp
Labels: dfs & bfs

#1510 250729 : [BOJ 12970] AB
  _sungyoon/12970.cpp
Labels: 그리디, 수학

#1506 250729 : [BOJ 12970] AB
  _hyunseo/12970.py
Labels: 그리디, 수학

#1515 250730 : [BOJ 1497] 기타콘서트
  _eunjin/1497_기타콘서트.py
Labels: 백트래킹
