Repository CTStudyGroup/BOJ, pull requests merged in 2025-03, with the labels that each got.

#544 250301 : [BOJ 11509] 풍선 맞추기 / G5
  _eunjin/eunjin_11509.py
Labels: 그리디

#549 250301 : [BOJ 2961] 도영이가 만든 맛있는 음식 / S2
  _eunjin/2961.py
Labels: 백트래킹

#534 250228 : [BOJ 28215] 대피소 / S4
  _eunjin/eunjin_28215.py
Labels: 브루트포스

#535 250228 : [BOJ 1213] 팰린드롬 만들기 / S3
  _eunjin/eunjin_1213.py
Labels: 구현, 문자열

#536 250228 : [BOJ 20300] 서강근육맨 / S3
  _eunjin/eunjin_20300.py
Labels: 정렬, 그리디

#538 구현 : [BOJ 17135] 캐슬 디펜스 / G3
  _eunjin/eunjin_17135.py
Labels: 브루트포스, dfs & bfs, 구현

#556 250303 : [BOJ 17615] 볼 모으기 / S1
  _eunjin/17615.py
Labels: 그리디

#557 250303 : [BOJ 1106] 호텔 / G4
  _eunjin/1106.py
Labels: 다이나믹프로그래밍

#558 250303 : [BOJ 2636] 치즈 / G4
  _hyolim/2636_치즈.c++
Labels: 구현

#559 250303 : [BOJ 17615] 볼 모으기 / S1
  _hyolim/16472_고냥이
  _hyolim/17615_볼모으기.c++
Labels: 그리디

#560 250303 : [BOJ 1106] 호텔 / G4
  _hyolim/1106_호텔.c++
Labels: 다이나믹프로그래밍

#561 250303 : [BOJ 13302] 리조트 / G4
  _eunjin/13302.py
Labels: 다이나믹프로그래밍

#562 250303 : [BOJ 13302] 리조트 / G4
  _hyolim/13302_리조트.c++
Labels: 다이나믹프로그래밍

#550 250302 : [BOJ 16953] A → B / S2
  _eunjin/16953.py
Labels: 그리디, dfs & bfs, 백트래킹

#551 250302 : [BOJ 1038] 감소하는 수 / G5
  _eunjin/1038.py
Labels: 브루트포스, 백트래킹

#555 250302 : [BOJ 1535] 안녕 / S2
  _eunjin/1535.py
Labels: 브루트포스, 다이나믹프로그래밍

#567 250304 : [BOJ 11501] 주식 / S2
  _eunjin/11501.py
Labels: 그리디

#569 250304 : [BOJ 15665] N과 M (11) / S2
  _eunjin/15665.py
Labels: 정렬, 백트래킹

#568 250304 : [BOJ 14713] 앵무새 / S2
  _eunjin/14713.py
Labels: 스택/큐

#572 250304 : [BOJ 15665] N과M(11) / S2
  _hyolim/15665_N과M(11).cpp
Labels: 순열

#570 구현 : [BOJ 17144] 미세먼지 안녕! / G4
  _eunjin/17144.py
Labels: 구현, 시뮬레이션

#578 250305 : [BOJ 14495] 피보나치 비스무리한 수열 / S4
  _hyolim/14495_피보나치비스무리한수열.c++
Labels: 다이나믹프로그래밍

#581 250305 : [BOJ 14495] 피보나치 비스무리한 수열
  _eunjin/14495.py
Labels: 다이나믹프로그래밍

#579 250305 : [BOJ 12931] 두 배 더하기
  _eunjin/12931.py
Labels: 그리디

#580 250305 : [BOJ 1522] 문자열 교환
  _eunjin/1522.py
Labels: 브루트포스, 슬라이딩윈도우

#582 구현 : [BOJ 2636] 치즈 / G4
  _eunjin/2636.py
Labels: dfs & bfs, 구현

#584 250305 : [BOJ 1522] 문자열 교한 / S1
  _hyolim/1522_문자열교환.c++
Labels: 브루트포스, 문자열

#583 250305 : [BOJ 12931] 두 배 더하기 / G5
  _hyolim/12931_두배더하기.c++
Labels: 그리디

#563 구현 : [BOJ 15683] 감시 / G3
  _eunjin/15683.py
Labels: 구현, 백트래킹

#585 250305 : [BOJ 15683] 감시 / G3
  _hyolim/15683_감시.c++
Labels: 재귀함수, 구현

#592 250307 : [BOJ 16139] 인간-컴퓨터 상호작용
  _eunjin/16139.py
Labels: 다이나믹프로그래밍

#595 250307 : [BOJ 23290] 마법사 상어와 복제
  _eunjin/23290.py
Labels: dfs & bfs, 구현, 백트래킹

#593 250307 : [BOJ 16139] 인간 컴퓨터 상호작용 / S1
  _hyolim/16139_인간컴퓨터상호작용.cpp
Labels: 다이나믹프로그래밍

#594 250307 : [BOJ 23290] 마법사 상어와 복제 / G1
  _hyolim/23290_마법사상어와복제.cpp
Labels: 구현

#605 250309 : [BOJ 1965] 상자넣기
  _hyolim/1965_상자넣기.cpp
Labels: 다이나믹프로그래밍

#590 250307 : [BOJ 14465] 소가 길을 건너간 이유 5
  _eunjin/14465.py
Labels: 슬라이딩윈도우

#617 250310 : [BOJ 1890] 점프
  _eunjin/1890.py
Labels: 다이나믹프로그래밍

#615 250310 : [BOJ 5904] Moo 게임
  _eunjin/5904.py
Labels: 재귀함수, 분할정복

#611 250310 : [BOJ 5904] moo 게임
  _hyolim/5904_MOO게임.c++
Labels: 분할정복

#612 250310 : [BOJ 26215] 눈치우기
  _hyolim/26215_눈치우기.cpp
Labels: 그리디

#613 250310 : [BOJ 1890] 점프
  _hyolim/1890_점프.cpp
Labels: 다이나믹프로그래밍

#622 250311 : [BOJ 24444] 알고리즘 수업 - 너비 우선 탐색 1
  _hyolim/24444_알고리즘수업너비우선탐색1.c++
Labels: dfs & bfs

#623 250311 : [BOJ 15489] 파스칼의 삼각형
  _hyolim/15489_파스칼의삼각형.c++
Labels: 다이나믹프로그래밍

#627 250311 : [BOJ 12101] 1,2,3더하기 2
  _hyolim/12101_1,2,3더하기2.c++
Labels: 브루트포스

#624 250311 : [BOJ 24444] 알고리즘 수업 - 너비 우선 탐색 1
  _eunjin/24444.py
Labels: dfs & bfs

#625 250311 : [BOJ 15489] 파스칼 삼각형
  _eunjin/15489.py
Labels: 다이나믹프로그래밍

#626 250311 : [BOJ 12101] 1, 2, 3 더하기 2
  _eunjin/12101.py
Labels: 백트래킹

#638 250312 : [BOJ 14430] 자원 캐기
  _eunjin/14430.py
Labels: 다이나믹프로그래밍

#614 250310 : [BOJ 12764] 싸지방에 간 준하
  _hyolim/12764_싸지방에간준하.cpp
Labels: 스택/큐

#628 250311 : [BOJ 9328] 열쇠
  _hyolim/9328_열쇠.c++
Labels: dfs & bfs, 구현

#639 250312 : [BOJ 14430] 자원캐기
  _hyolim/14430_자원캐기.c++
Labels: 다이나믹프로그래밍

#640 250312 : [BOJ 1793] 타일링
  _hyolim/1793_타일링.cpp
Labels: 다이나믹프로그래밍, 문자열

#656 250312 : [BOJ 1036] 36진수
  _hyolim/1036_36진수.c++
Labels: 정렬, 그리디, 구현

#657 250317 : [BOJ 17204] 죽음의 게임
  _hyolim/17204_죽음의게임.cpp
Labels: dfs & bfs

#662 250318 : [BOJ 7795] 먹을 것인가 먹힐 것인가
  _hyolim/7795_먹을것인가먹힐것인가.cpp
Labels: 정렬, 백트래킹

#663 Create 1235_학생번호.cpp
  _hyolim/1235_학생번호.cpp
Labels: 브루트포스

#677 250321 : [BOJ 25418] 정수 a를 k로 만들기
  _hyolim/25418_정수a를k로만들기.C++
Labels: dfs & bfs

#678 250321 : [BOJ 15723] n단 논법
  _eunjin/15723.py
Labels: dfs & bfs

#687 ⭐️ 250324 : [BOJ 16507] 어두운 건 무서워
  _eunjin/eunjin_16507.py
Labels: 다이나믹프로그래밍

#688 ⭐️ 250324 : [BOJ 16235] 나무 재테크
  _hyolim/16235_나무재테크.c++
Labels: 구현

#690 ⭐️ 250324 : [BOJ 16235] 나무 재테크
  _eunjin/eunjin_16235.py
Labels: 구현, 시뮬레이션

#691 ⭐️ 250324 : [BOJ 16507] 어두운 건 무서워
  _sungyoon/16507.cpp
Labels: 다이나믹프로그래밍

#692 250324 : [BOJ 11060] 점프 점프
  _sungyoon/11060.cpp
Labels: dfs & bfs

#693 250324 : [BOJ 11441] 합 구하기
  _sungyoon/11441.cpp
Labels: 다이나믹프로그래밍

#698 250325 : [BOJ 10800] 컬러볼
  _hyolim/10800_컬러볼.cpp
Labels: 정렬, 다이나믹프로그래밍

#699 250325 : [BOJ 12933] 오리
  _hyolim/12933_오리.cpp
Labels: 구현, 문자열

#707 ⭐️ 250326 : [BOJ 14675] 단절점과 단절선
  _hyolim/14675_단절점과단절선.cpp
Labels: 트리

#706 ⭐️ 250326 : [BOJ 16985] Maaaaaaaaaze
  _eunjin/eunjin_16985.py
Labels: 순열, dfs & bfs, 구현

#717 ⭐️ 250328 : [BOJ 3967] 매직 스타
  _hyolim/3967_매직스타.cpp
Labels: 재귀함수, 순열, 구현
